//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/JLaTeXMath-iOS/JLaTeXMath-iOS/jlatexmath-share/org/scilab/forge/jlatexmath/platform/graphics/GraphicsFactory.java
//

#ifndef _OrgScilabForgeJlatexmathPlatformGraphicsGraphicsFactory_H_
#define _OrgScilabForgeJlatexmathPlatformGraphicsGraphicsFactory_H_

#include "J2ObjC_header.h"

@protocol OrgScilabForgeJlatexmathPlatformGraphicsBasicStroke;
@protocol OrgScilabForgeJlatexmathPlatformGraphicsColor;
@protocol OrgScilabForgeJlatexmathPlatformGraphicsImage;
@protocol OrgScilabForgeJlatexmathPlatformGraphicsTransform;

@interface OrgScilabForgeJlatexmathPlatformGraphicsGraphicsFactory : NSObject

#pragma mark Public

- (instancetype)init;

- (id<OrgScilabForgeJlatexmathPlatformGraphicsBasicStroke>)createBasicStrokeWithFloat:(jfloat)width
                                                                              withInt:(jint)cap
                                                                              withInt:(jint)join
                                                                            withFloat:(jfloat)miterLimit;

- (id<OrgScilabForgeJlatexmathPlatformGraphicsColor>)createColorWithInt:(jint)red
                                                                withInt:(jint)green
                                                                withInt:(jint)blue;

- (id<OrgScilabForgeJlatexmathPlatformGraphicsImage>)createImageWithInt:(jint)width
                                                                withInt:(jint)height
                                                                withInt:(jint)type;

- (id<OrgScilabForgeJlatexmathPlatformGraphicsTransform>)createTransform;

- (id<OrgScilabForgeJlatexmathPlatformGraphicsImage>)getImageWithNSString:(NSString *)path;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgScilabForgeJlatexmathPlatformGraphicsGraphicsFactory)

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathPlatformGraphicsGraphicsFactory_init(OrgScilabForgeJlatexmathPlatformGraphicsGraphicsFactory *self);

J2OBJC_TYPE_LITERAL_HEADER(OrgScilabForgeJlatexmathPlatformGraphicsGraphicsFactory)

#endif // _OrgScilabForgeJlatexmathPlatformGraphicsGraphicsFactory_H_
