//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/scilab/forge/jlatexmath/exception/AlphabetRegistrationException.java
//

#ifndef _OrgScilabForgeJlatexmathExceptionAlphabetRegistrationException_H_
#define _OrgScilabForgeJlatexmathExceptionAlphabetRegistrationException_H_

#include "J2ObjC_header.h"
#include "java/lang/Exception.h"

@interface OrgScilabForgeJlatexmathExceptionAlphabetRegistrationException : JavaLangException

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)str;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgScilabForgeJlatexmathExceptionAlphabetRegistrationException)

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathExceptionAlphabetRegistrationException_initWithNSString_(OrgScilabForgeJlatexmathExceptionAlphabetRegistrationException *self, NSString *str);

FOUNDATION_EXPORT OrgScilabForgeJlatexmathExceptionAlphabetRegistrationException *new_OrgScilabForgeJlatexmathExceptionAlphabetRegistrationException_initWithNSString_(NSString *str) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgScilabForgeJlatexmathExceptionAlphabetRegistrationException)

#endif // _OrgScilabForgeJlatexmathExceptionAlphabetRegistrationException_H_
