//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/scilab/forge/jlatexmath/cyrillic/CyrillicRegistration.java
//


#include "Character.h"
#include "CyrillicRegistration.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"

@implementation OrgScilabForgeJlatexmathCyrillicCyrillicRegistration

- (instancetype)init {
  OrgScilabForgeJlatexmathCyrillicCyrillicRegistration_init(self);
  return self;
}

- (IOSObjectArray *)getUnicodeBlock {
  return [IOSObjectArray newArrayWithObjects:(id[]){ OrgScilabForgeJlatexmathCharacterCharacter_UnicodeBlock_get_CYRILLIC_() } count:1 type:OrgScilabForgeJlatexmathCharacterCharacter_UnicodeBlock_class_()];
}

- (id)getPackage {
  return OrgScilabForgeJlatexmathCyrillicCyrillicRegistration_class_();
}

- (NSString *)getTeXFontFileName {
  return @"fonts/language_cyrillic.xml";
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "CyrillicRegistration", NULL, 0x1, NULL, NULL },
    { "getUnicodeBlock", NULL, "[Lorg.scilab.forge.jlatexmath.character.Character$UnicodeBlock;", 0x1, NULL, NULL },
    { "getPackage", NULL, "Ljava.lang.Object;", 0x1, NULL, NULL },
    { "getTeXFontFileName", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
  };
  static const J2ObjcClassInfo _OrgScilabForgeJlatexmathCyrillicCyrillicRegistration = { 2, "CyrillicRegistration", "org.scilab.forge.jlatexmath.cyrillic", NULL, 0x1, 4, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgScilabForgeJlatexmathCyrillicCyrillicRegistration;
}

@end

void OrgScilabForgeJlatexmathCyrillicCyrillicRegistration_init(OrgScilabForgeJlatexmathCyrillicCyrillicRegistration *self) {
  (void) NSObject_init(self);
}

OrgScilabForgeJlatexmathCyrillicCyrillicRegistration *new_OrgScilabForgeJlatexmathCyrillicCyrillicRegistration_init() {
  OrgScilabForgeJlatexmathCyrillicCyrillicRegistration *self = [OrgScilabForgeJlatexmathCyrillicCyrillicRegistration alloc];
  OrgScilabForgeJlatexmathCyrillicCyrillicRegistration_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgScilabForgeJlatexmathCyrillicCyrillicRegistration)
