//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/scilab/forge/jlatexmath/Extension.java
//


#include "Char.h"
#include "Extension.h"
#include "J2ObjC_source.h"

@interface OrgScilabForgeJlatexmathExtension () {
 @public
  OrgScilabForgeJlatexmathChar *top_;
  OrgScilabForgeJlatexmathChar *middle_;
  OrgScilabForgeJlatexmathChar *bottom_;
  OrgScilabForgeJlatexmathChar *repeat_;
}

@end

J2OBJC_FIELD_SETTER(OrgScilabForgeJlatexmathExtension, top_, OrgScilabForgeJlatexmathChar *)
J2OBJC_FIELD_SETTER(OrgScilabForgeJlatexmathExtension, middle_, OrgScilabForgeJlatexmathChar *)
J2OBJC_FIELD_SETTER(OrgScilabForgeJlatexmathExtension, bottom_, OrgScilabForgeJlatexmathChar *)
J2OBJC_FIELD_SETTER(OrgScilabForgeJlatexmathExtension, repeat_, OrgScilabForgeJlatexmathChar *)

@implementation OrgScilabForgeJlatexmathExtension

- (instancetype)initWithOrgScilabForgeJlatexmathChar:(OrgScilabForgeJlatexmathChar *)t
                    withOrgScilabForgeJlatexmathChar:(OrgScilabForgeJlatexmathChar *)m
                    withOrgScilabForgeJlatexmathChar:(OrgScilabForgeJlatexmathChar *)r
                    withOrgScilabForgeJlatexmathChar:(OrgScilabForgeJlatexmathChar *)b {
  OrgScilabForgeJlatexmathExtension_initWithOrgScilabForgeJlatexmathChar_withOrgScilabForgeJlatexmathChar_withOrgScilabForgeJlatexmathChar_withOrgScilabForgeJlatexmathChar_(self, t, m, r, b);
  return self;
}

- (jboolean)hasTop {
  return top_ != nil;
}

- (jboolean)hasMiddle {
  return middle_ != nil;
}

- (jboolean)hasBottom {
  return bottom_ != nil;
}

- (OrgScilabForgeJlatexmathChar *)getTop {
  return top_;
}

- (OrgScilabForgeJlatexmathChar *)getMiddle {
  return middle_;
}

- (OrgScilabForgeJlatexmathChar *)getRepeat {
  return repeat_;
}

- (OrgScilabForgeJlatexmathChar *)getBottom {
  return bottom_;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithOrgScilabForgeJlatexmathChar:withOrgScilabForgeJlatexmathChar:withOrgScilabForgeJlatexmathChar:withOrgScilabForgeJlatexmathChar:", "Extension", NULL, 0x1, NULL, NULL },
    { "hasTop", NULL, "Z", 0x1, NULL, NULL },
    { "hasMiddle", NULL, "Z", 0x1, NULL, NULL },
    { "hasBottom", NULL, "Z", 0x1, NULL, NULL },
    { "getTop", NULL, "Lorg.scilab.forge.jlatexmath.Char;", 0x1, NULL, NULL },
    { "getMiddle", NULL, "Lorg.scilab.forge.jlatexmath.Char;", 0x1, NULL, NULL },
    { "getRepeat", NULL, "Lorg.scilab.forge.jlatexmath.Char;", 0x1, NULL, NULL },
    { "getBottom", NULL, "Lorg.scilab.forge.jlatexmath.Char;", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "top_", NULL, 0x12, "Lorg.scilab.forge.jlatexmath.Char;", NULL, NULL,  },
    { "middle_", NULL, 0x12, "Lorg.scilab.forge.jlatexmath.Char;", NULL, NULL,  },
    { "bottom_", NULL, 0x12, "Lorg.scilab.forge.jlatexmath.Char;", NULL, NULL,  },
    { "repeat_", NULL, 0x12, "Lorg.scilab.forge.jlatexmath.Char;", NULL, NULL,  },
  };
  static const J2ObjcClassInfo _OrgScilabForgeJlatexmathExtension = { 2, "Extension", "org.scilab.forge.jlatexmath", NULL, 0x1, 8, methods, 4, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgScilabForgeJlatexmathExtension;
}

@end

void OrgScilabForgeJlatexmathExtension_initWithOrgScilabForgeJlatexmathChar_withOrgScilabForgeJlatexmathChar_withOrgScilabForgeJlatexmathChar_withOrgScilabForgeJlatexmathChar_(OrgScilabForgeJlatexmathExtension *self, OrgScilabForgeJlatexmathChar *t, OrgScilabForgeJlatexmathChar *m, OrgScilabForgeJlatexmathChar *r, OrgScilabForgeJlatexmathChar *b) {
  (void) NSObject_init(self);
  self->top_ = t;
  self->middle_ = m;
  self->repeat_ = r;
  self->bottom_ = b;
}

OrgScilabForgeJlatexmathExtension *new_OrgScilabForgeJlatexmathExtension_initWithOrgScilabForgeJlatexmathChar_withOrgScilabForgeJlatexmathChar_withOrgScilabForgeJlatexmathChar_withOrgScilabForgeJlatexmathChar_(OrgScilabForgeJlatexmathChar *t, OrgScilabForgeJlatexmathChar *m, OrgScilabForgeJlatexmathChar *r, OrgScilabForgeJlatexmathChar *b) {
  OrgScilabForgeJlatexmathExtension *self = [OrgScilabForgeJlatexmathExtension alloc];
  OrgScilabForgeJlatexmathExtension_initWithOrgScilabForgeJlatexmathChar_withOrgScilabForgeJlatexmathChar_withOrgScilabForgeJlatexmathChar_withOrgScilabForgeJlatexmathChar_(self, t, m, r, b);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgScilabForgeJlatexmathExtension)
