//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/scilab/forge/jlatexmath/dynamic/ExternalConverter.java
//

#ifndef _OrgScilabForgeJlatexmathDynamicExternalConverter_H_
#define _OrgScilabForgeJlatexmathDynamicExternalConverter_H_

#include "J2ObjC_header.h"

@protocol OrgScilabForgeJlatexmathDynamicExternalConverter < NSObject, JavaObject >

- (NSString *)getLaTeXStringWithNSString:(NSString *)externalCode;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgScilabForgeJlatexmathDynamicExternalConverter)

J2OBJC_TYPE_LITERAL_HEADER(OrgScilabForgeJlatexmathDynamicExternalConverter)

#endif // _OrgScilabForgeJlatexmathDynamicExternalConverter_H_
