//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/scilab/forge/jlatexmath/platform/graphics/Insets.java
//

#ifndef _OrgScilabForgeJlatexmathPlatformGraphicsInsets_H_
#define _OrgScilabForgeJlatexmathPlatformGraphicsInsets_H_

#include "J2ObjC_header.h"

@interface OrgScilabForgeJlatexmathPlatformGraphicsInsets : NSObject {
 @public
  jint top_, left_, bottom_, right_;
}

#pragma mark Public

- (instancetype)initWithInt:(jint)top
                    withInt:(jint)left
                    withInt:(jint)bottom
                    withInt:(jint)right;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgScilabForgeJlatexmathPlatformGraphicsInsets)

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathPlatformGraphicsInsets_initWithInt_withInt_withInt_withInt_(OrgScilabForgeJlatexmathPlatformGraphicsInsets *self, jint top, jint left, jint bottom, jint right);

FOUNDATION_EXPORT OrgScilabForgeJlatexmathPlatformGraphicsInsets *new_OrgScilabForgeJlatexmathPlatformGraphicsInsets_initWithInt_withInt_withInt_withInt_(jint top, jint left, jint bottom, jint right) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgScilabForgeJlatexmathPlatformGraphicsInsets)

#endif // _OrgScilabForgeJlatexmathPlatformGraphicsInsets_H_
