//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/scilab/forge/jlatexmath/exception/InvalidTeXFormulaException.java
//

#ifndef _OrgScilabForgeJlatexmathExceptionInvalidTeXFormulaException_H_
#define _OrgScilabForgeJlatexmathExceptionInvalidTeXFormulaException_H_

#include "J2ObjC_header.h"
#include "JMathTeXException.h"

@interface OrgScilabForgeJlatexmathExceptionInvalidTeXFormulaException : OrgScilabForgeJlatexmathExceptionJMathTeXException

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)msg;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgScilabForgeJlatexmathExceptionInvalidTeXFormulaException)

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathExceptionInvalidTeXFormulaException_initWithNSString_(OrgScilabForgeJlatexmathExceptionInvalidTeXFormulaException *self, NSString *msg);

FOUNDATION_EXPORT OrgScilabForgeJlatexmathExceptionInvalidTeXFormulaException *new_OrgScilabForgeJlatexmathExceptionInvalidTeXFormulaException_initWithNSString_(NSString *msg) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgScilabForgeJlatexmathExceptionInvalidTeXFormulaException)

#endif // _OrgScilabForgeJlatexmathExceptionInvalidTeXFormulaException_H_
