//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/scilab/forge/jlatexmath/exception/InvalidDelimiterTypeException.java
//


#include "InvalidDelimiterTypeException.h"
#include "J2ObjC_source.h"
#include "JMathTeXException.h"

@implementation OrgScilabForgeJlatexmathExceptionInvalidDelimiterTypeException

- (instancetype)init {
  OrgScilabForgeJlatexmathExceptionInvalidDelimiterTypeException_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "InvalidDelimiterTypeException", NULL, 0x4, NULL, NULL },
  };
  static const J2ObjcClassInfo _OrgScilabForgeJlatexmathExceptionInvalidDelimiterTypeException = { 2, "InvalidDelimiterTypeException", "org.scilab.forge.jlatexmath.exception", NULL, 0x1, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgScilabForgeJlatexmathExceptionInvalidDelimiterTypeException;
}

@end

void OrgScilabForgeJlatexmathExceptionInvalidDelimiterTypeException_init(OrgScilabForgeJlatexmathExceptionInvalidDelimiterTypeException *self) {
  (void) OrgScilabForgeJlatexmathExceptionJMathTeXException_initWithNSString_(self, @"The delimiter type was not valid! Use one of the delimiter type constants from the class 'TeXConstants'.");
}

OrgScilabForgeJlatexmathExceptionInvalidDelimiterTypeException *new_OrgScilabForgeJlatexmathExceptionInvalidDelimiterTypeException_init() {
  OrgScilabForgeJlatexmathExceptionInvalidDelimiterTypeException *self = [OrgScilabForgeJlatexmathExceptionInvalidDelimiterTypeException alloc];
  OrgScilabForgeJlatexmathExceptionInvalidDelimiterTypeException_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgScilabForgeJlatexmathExceptionInvalidDelimiterTypeException)
