//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/scilab/forge/jlatexmath/exception/InvalidUnitException.java
//


#include "InvalidUnitException.h"
#include "J2ObjC_source.h"
#include "JMathTeXException.h"

@implementation OrgScilabForgeJlatexmathExceptionInvalidUnitException

- (instancetype)init {
  OrgScilabForgeJlatexmathExceptionInvalidUnitException_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "InvalidUnitException", NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcClassInfo _OrgScilabForgeJlatexmathExceptionInvalidUnitException = { 2, "InvalidUnitException", "org.scilab.forge.jlatexmath.exception", NULL, 0x1, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgScilabForgeJlatexmathExceptionInvalidUnitException;
}

@end

void OrgScilabForgeJlatexmathExceptionInvalidUnitException_init(OrgScilabForgeJlatexmathExceptionInvalidUnitException *self) {
  (void) OrgScilabForgeJlatexmathExceptionJMathTeXException_initWithNSString_(self, @"The delimiter type was not valid! Use one of the unit constants from the class 'TeXConstants'.");
}

OrgScilabForgeJlatexmathExceptionInvalidUnitException *new_OrgScilabForgeJlatexmathExceptionInvalidUnitException_init() {
  OrgScilabForgeJlatexmathExceptionInvalidUnitException *self = [OrgScilabForgeJlatexmathExceptionInvalidUnitException alloc];
  OrgScilabForgeJlatexmathExceptionInvalidUnitException_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgScilabForgeJlatexmathExceptionInvalidUnitException)
