//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/scilab/forge/jlatexmath/PhantomAtom.java
//


#include "Atom.h"
#include "Box.h"
#include "Dummy.h"
#include "J2ObjC_source.h"
#include "PhantomAtom.h"
#include "RowAtom.h"
#include "StrutBox.h"
#include "TeXEnvironment.h"

@interface OrgScilabForgeJlatexmathPhantomAtom () {
 @public
  OrgScilabForgeJlatexmathRowAtom *elements_;
  jboolean w_, h_, d_;
}

@end

J2OBJC_FIELD_SETTER(OrgScilabForgeJlatexmathPhantomAtom, elements_, OrgScilabForgeJlatexmathRowAtom *)

@implementation OrgScilabForgeJlatexmathPhantomAtom

- (instancetype)initWithOrgScilabForgeJlatexmathAtom:(OrgScilabForgeJlatexmathAtom *)el {
  OrgScilabForgeJlatexmathPhantomAtom_initWithOrgScilabForgeJlatexmathAtom_(self, el);
  return self;
}

- (instancetype)initWithOrgScilabForgeJlatexmathAtom:(OrgScilabForgeJlatexmathAtom *)el
                                         withBoolean:(jboolean)width
                                         withBoolean:(jboolean)height
                                         withBoolean:(jboolean)depth {
  OrgScilabForgeJlatexmathPhantomAtom_initWithOrgScilabForgeJlatexmathAtom_withBoolean_withBoolean_withBoolean_(self, el, width, height, depth);
  return self;
}

- (OrgScilabForgeJlatexmathBox *)createBoxWithOrgScilabForgeJlatexmathTeXEnvironment:(OrgScilabForgeJlatexmathTeXEnvironment *)env {
  OrgScilabForgeJlatexmathBox *res = [((OrgScilabForgeJlatexmathRowAtom *) nil_chk(elements_)) createBoxWithOrgScilabForgeJlatexmathTeXEnvironment:env];
  return new_OrgScilabForgeJlatexmathStrutBox_initWithFloat_withFloat_withFloat_withFloat_((w_ ? [((OrgScilabForgeJlatexmathBox *) nil_chk(res)) getWidth] : 0), (h_ ? [((OrgScilabForgeJlatexmathBox *) nil_chk(res)) getHeight] : 0), (d_ ? [((OrgScilabForgeJlatexmathBox *) nil_chk(res)) getDepth] : 0), [((OrgScilabForgeJlatexmathBox *) nil_chk(res)) getShift]);
}

- (jint)getLeftType {
  return [((OrgScilabForgeJlatexmathRowAtom *) nil_chk(elements_)) getLeftType];
}

- (jint)getRightType {
  return [((OrgScilabForgeJlatexmathRowAtom *) nil_chk(elements_)) getRightType];
}

- (void)setPreviousAtomWithOrgScilabForgeJlatexmathDummy:(OrgScilabForgeJlatexmathDummy *)prev {
  [((OrgScilabForgeJlatexmathRowAtom *) nil_chk(elements_)) setPreviousAtomWithOrgScilabForgeJlatexmathDummy:prev];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithOrgScilabForgeJlatexmathAtom:", "PhantomAtom", NULL, 0x1, NULL, NULL },
    { "initWithOrgScilabForgeJlatexmathAtom:withBoolean:withBoolean:withBoolean:", "PhantomAtom", NULL, 0x1, NULL, NULL },
    { "createBoxWithOrgScilabForgeJlatexmathTeXEnvironment:", "createBox", "Lorg.scilab.forge.jlatexmath.Box;", 0x1, NULL, NULL },
    { "getLeftType", NULL, "I", 0x1, NULL, NULL },
    { "getRightType", NULL, "I", 0x1, NULL, NULL },
    { "setPreviousAtomWithOrgScilabForgeJlatexmathDummy:", "setPreviousAtom", "V", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "elements_", NULL, 0x2, "Lorg.scilab.forge.jlatexmath.RowAtom;", NULL, NULL,  },
    { "w_", NULL, 0x2, "Z", NULL, NULL,  },
    { "h_", NULL, 0x2, "Z", NULL, NULL,  },
    { "d_", NULL, 0x2, "Z", NULL, NULL,  },
  };
  static const J2ObjcClassInfo _OrgScilabForgeJlatexmathPhantomAtom = { 2, "PhantomAtom", "org.scilab.forge.jlatexmath", NULL, 0x1, 6, methods, 4, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgScilabForgeJlatexmathPhantomAtom;
}

@end

void OrgScilabForgeJlatexmathPhantomAtom_initWithOrgScilabForgeJlatexmathAtom_(OrgScilabForgeJlatexmathPhantomAtom *self, OrgScilabForgeJlatexmathAtom *el) {
  (void) OrgScilabForgeJlatexmathAtom_init(self);
  self->w_ = YES;
  self->h_ = YES;
  self->d_ = YES;
  if (el == nil) self->elements_ = new_OrgScilabForgeJlatexmathRowAtom_init();
  else self->elements_ = new_OrgScilabForgeJlatexmathRowAtom_initWithOrgScilabForgeJlatexmathAtom_(el);
}

OrgScilabForgeJlatexmathPhantomAtom *new_OrgScilabForgeJlatexmathPhantomAtom_initWithOrgScilabForgeJlatexmathAtom_(OrgScilabForgeJlatexmathAtom *el) {
  OrgScilabForgeJlatexmathPhantomAtom *self = [OrgScilabForgeJlatexmathPhantomAtom alloc];
  OrgScilabForgeJlatexmathPhantomAtom_initWithOrgScilabForgeJlatexmathAtom_(self, el);
  return self;
}

void OrgScilabForgeJlatexmathPhantomAtom_initWithOrgScilabForgeJlatexmathAtom_withBoolean_withBoolean_withBoolean_(OrgScilabForgeJlatexmathPhantomAtom *self, OrgScilabForgeJlatexmathAtom *el, jboolean width, jboolean height, jboolean depth) {
  (void) OrgScilabForgeJlatexmathPhantomAtom_initWithOrgScilabForgeJlatexmathAtom_(self, el);
  self->w_ = width;
  self->h_ = height;
  self->d_ = depth;
}

OrgScilabForgeJlatexmathPhantomAtom *new_OrgScilabForgeJlatexmathPhantomAtom_initWithOrgScilabForgeJlatexmathAtom_withBoolean_withBoolean_withBoolean_(OrgScilabForgeJlatexmathAtom *el, jboolean width, jboolean height, jboolean depth) {
  OrgScilabForgeJlatexmathPhantomAtom *self = [OrgScilabForgeJlatexmathPhantomAtom alloc];
  OrgScilabForgeJlatexmathPhantomAtom_initWithOrgScilabForgeJlatexmathAtom_withBoolean_withBoolean_withBoolean_(self, el, width, height, depth);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgScilabForgeJlatexmathPhantomAtom)
