//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/scilab/forge/jlatexmath/PredefinedTeXFormulaParser.java
//

#ifndef _OrgScilabForgeJlatexmathPredefinedTeXFormulaParser_H_
#define _OrgScilabForgeJlatexmathPredefinedTeXFormulaParser_H_

#include "J2ObjC_header.h"

@protocol JavaUtilMap;

@interface OrgScilabForgeJlatexmathPredefinedTeXFormulaParser : NSObject

#pragma mark Public

- (instancetype)initWithId:(id)file
              withNSString:(NSString *)type;

- (instancetype)initWithNSString:(NSString *)PredefFile
                    withNSString:(NSString *)type;

- (void)parseWithJavaUtilMap:(id<JavaUtilMap>)predefinedTeXFormulas;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgScilabForgeJlatexmathPredefinedTeXFormulaParser)

FOUNDATION_EXPORT NSString *OrgScilabForgeJlatexmathPredefinedTeXFormulaParser_RESOURCE_NAME_;
J2OBJC_STATIC_FIELD_GETTER(OrgScilabForgeJlatexmathPredefinedTeXFormulaParser, RESOURCE_NAME_, NSString *)

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathPredefinedTeXFormulaParser_initWithId_withNSString_(OrgScilabForgeJlatexmathPredefinedTeXFormulaParser *self, id file, NSString *type);

FOUNDATION_EXPORT OrgScilabForgeJlatexmathPredefinedTeXFormulaParser *new_OrgScilabForgeJlatexmathPredefinedTeXFormulaParser_initWithId_withNSString_(id file, NSString *type) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathPredefinedTeXFormulaParser_initWithNSString_withNSString_(OrgScilabForgeJlatexmathPredefinedTeXFormulaParser *self, NSString *PredefFile, NSString *type);

FOUNDATION_EXPORT OrgScilabForgeJlatexmathPredefinedTeXFormulaParser *new_OrgScilabForgeJlatexmathPredefinedTeXFormulaParser_initWithNSString_withNSString_(NSString *PredefFile, NSString *type) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgScilabForgeJlatexmathPredefinedTeXFormulaParser)

#endif // _OrgScilabForgeJlatexmathPredefinedTeXFormulaParser_H_
