//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/scilab/forge/jlatexmath/platform/geom/Rectangle2D.java
//


#include "J2ObjC_source.h"
#include "Rectangle2D.h"

@interface OrgScilabForgeJlatexmathPlatformGeomRectangle2D : NSObject
@end

@interface OrgScilabForgeJlatexmathPlatformGeomRectangle2D_Float : NSObject
@end

@implementation OrgScilabForgeJlatexmathPlatformGeomRectangle2D

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getX", NULL, "D", 0x401, NULL, NULL },
    { "getY", NULL, "D", 0x401, NULL, NULL },
    { "getWidth", NULL, "D", 0x401, NULL, NULL },
    { "getHeight", NULL, "D", 0x401, NULL, NULL },
    { "setRectangleWithDouble:withDouble:withDouble:withDouble:", "setRectangle", "V", 0x401, NULL, NULL },
  };
  static const char *inner_classes[] = {"Lorg.scilab.forge.jlatexmath.platform.geom.Rectangle2D$Float;"};
  static const J2ObjcClassInfo _OrgScilabForgeJlatexmathPlatformGeomRectangle2D = { 2, "Rectangle2D", "org.scilab.forge.jlatexmath.platform.geom", NULL, 0x609, 5, methods, 0, NULL, 0, NULL, 1, inner_classes, NULL, NULL };
  return &_OrgScilabForgeJlatexmathPlatformGeomRectangle2D;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgScilabForgeJlatexmathPlatformGeomRectangle2D)

@implementation OrgScilabForgeJlatexmathPlatformGeomRectangle2D_Float

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcClassInfo _OrgScilabForgeJlatexmathPlatformGeomRectangle2D_Float = { 2, "Float", "org.scilab.forge.jlatexmath.platform.geom", "Rectangle2D", 0x609, 0, NULL, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgScilabForgeJlatexmathPlatformGeomRectangle2D_Float;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgScilabForgeJlatexmathPlatformGeomRectangle2D_Float)
