//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/scilab/forge/jlatexmath/regex/RegexUtil.java
//

#ifndef _OrgScilabForgeJlatexmathRegexRegexUtil_H_
#define _OrgScilabForgeJlatexmathRegexRegexUtil_H_

#include "J2ObjC_header.h"

@interface OrgScilabForgeJlatexmathRegexRegexUtil : NSObject

#pragma mark Public

- (instancetype)init;

+ (NSString *)quoteReplacementWithNSString:(NSString *)s;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgScilabForgeJlatexmathRegexRegexUtil)

FOUNDATION_EXPORT NSString *OrgScilabForgeJlatexmathRegexRegexUtil_quoteReplacementWithNSString_(NSString *s);

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathRegexRegexUtil_init(OrgScilabForgeJlatexmathRegexRegexUtil *self);

FOUNDATION_EXPORT OrgScilabForgeJlatexmathRegexRegexUtil *new_OrgScilabForgeJlatexmathRegexRegexUtil_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgScilabForgeJlatexmathRegexRegexUtil)

#endif // _OrgScilabForgeJlatexmathRegexRegexUtil_H_
