//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/scilab/forge/jlatexmath/exception/ResourceParseException.java
//


#include "J2ObjC_source.h"
#include "JMathTeXException.h"
#include "ResourceParseException.h"
#include "java/lang/Throwable.h"

@implementation OrgScilabForgeJlatexmathExceptionResourceParseException

- (instancetype)initWithNSString:(NSString *)msg {
  OrgScilabForgeJlatexmathExceptionResourceParseException_initWithNSString_(self, msg);
  return self;
}

- (instancetype)initWithNSString:(NSString *)msg
           withJavaLangThrowable:(JavaLangThrowable *)cause {
  OrgScilabForgeJlatexmathExceptionResourceParseException_initWithNSString_withJavaLangThrowable_(self, msg, cause);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithNSString:", "ResourceParseException", NULL, 0x1, NULL, NULL },
    { "initWithNSString:withJavaLangThrowable:", "ResourceParseException", NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcClassInfo _OrgScilabForgeJlatexmathExceptionResourceParseException = { 2, "ResourceParseException", "org.scilab.forge.jlatexmath.exception", NULL, 0x1, 2, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgScilabForgeJlatexmathExceptionResourceParseException;
}

@end

void OrgScilabForgeJlatexmathExceptionResourceParseException_initWithNSString_(OrgScilabForgeJlatexmathExceptionResourceParseException *self, NSString *msg) {
  (void) OrgScilabForgeJlatexmathExceptionJMathTeXException_initWithNSString_(self, msg);
}

OrgScilabForgeJlatexmathExceptionResourceParseException *new_OrgScilabForgeJlatexmathExceptionResourceParseException_initWithNSString_(NSString *msg) {
  OrgScilabForgeJlatexmathExceptionResourceParseException *self = [OrgScilabForgeJlatexmathExceptionResourceParseException alloc];
  OrgScilabForgeJlatexmathExceptionResourceParseException_initWithNSString_(self, msg);
  return self;
}

void OrgScilabForgeJlatexmathExceptionResourceParseException_initWithNSString_withJavaLangThrowable_(OrgScilabForgeJlatexmathExceptionResourceParseException *self, NSString *msg, JavaLangThrowable *cause) {
  (void) OrgScilabForgeJlatexmathExceptionJMathTeXException_initWithNSString_withJavaLangThrowable_(self, msg, cause);
}

OrgScilabForgeJlatexmathExceptionResourceParseException *new_OrgScilabForgeJlatexmathExceptionResourceParseException_initWithNSString_withJavaLangThrowable_(NSString *msg, JavaLangThrowable *cause) {
  OrgScilabForgeJlatexmathExceptionResourceParseException *self = [OrgScilabForgeJlatexmathExceptionResourceParseException alloc];
  OrgScilabForgeJlatexmathExceptionResourceParseException_initWithNSString_withJavaLangThrowable_(self, msg, cause);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgScilabForgeJlatexmathExceptionResourceParseException)
