//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/scilab/forge/jlatexmath/platform/Resource.java
//

#ifndef _OrgScilabForgeJlatexmathPlatformResource_H_
#define _OrgScilabForgeJlatexmathPlatformResource_H_

#include "J2ObjC_header.h"

@interface OrgScilabForgeJlatexmathPlatformResource : NSObject

#pragma mark Public

- (instancetype)init;

- (id)loadResourceWithId:(id)base
            withNSString:(NSString *)path;

- (id)loadResourceWithNSString:(NSString *)path;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgScilabForgeJlatexmathPlatformResource)

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathPlatformResource_init(OrgScilabForgeJlatexmathPlatformResource *self);

FOUNDATION_EXPORT OrgScilabForgeJlatexmathPlatformResource *new_OrgScilabForgeJlatexmathPlatformResource_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgScilabForgeJlatexmathPlatformResource)

#endif // _OrgScilabForgeJlatexmathPlatformResource_H_
