//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/scilab/forge/jlatexmath/platform/resources/ResourceLoaderFactory.java
//


#include "J2ObjC_source.h"
#include "ResourceLoader.h"
#include "ResourceLoaderFactory.h"

@interface OrgScilabForgeJlatexmathPlatformResourcesResourceLoaderFactory : NSObject
@end

@implementation OrgScilabForgeJlatexmathPlatformResourcesResourceLoaderFactory

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "createResourceLoader", NULL, "Lorg.scilab.forge.jlatexmath.platform.resources.ResourceLoader;", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _OrgScilabForgeJlatexmathPlatformResourcesResourceLoaderFactory = { 2, "ResourceLoaderFactory", "org.scilab.forge.jlatexmath.platform.resources", NULL, 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgScilabForgeJlatexmathPlatformResourcesResourceLoaderFactory;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgScilabForgeJlatexmathPlatformResourcesResourceLoaderFactory)
