//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/scilab/forge/jlatexmath/RotateAtom.java
//

#ifndef _OrgScilabForgeJlatexmathRotateAtom_H_
#define _OrgScilabForgeJlatexmathRotateAtom_H_

#include "Atom.h"
#include "J2ObjC_header.h"

@class OrgScilabForgeJlatexmathBox;
@class OrgScilabForgeJlatexmathTeXEnvironment;

@interface OrgScilabForgeJlatexmathRotateAtom : OrgScilabForgeJlatexmathAtom

#pragma mark Public

- (instancetype)initWithOrgScilabForgeJlatexmathAtom:(OrgScilabForgeJlatexmathAtom *)base
                                          withDouble:(jdouble)angle
                                        withNSString:(NSString *)option;

- (instancetype)initWithOrgScilabForgeJlatexmathAtom:(OrgScilabForgeJlatexmathAtom *)base
                                        withNSString:(NSString *)angle
                                        withNSString:(NSString *)option;

- (OrgScilabForgeJlatexmathBox *)createBoxWithOrgScilabForgeJlatexmathTeXEnvironment:(OrgScilabForgeJlatexmathTeXEnvironment *)env;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgScilabForgeJlatexmathRotateAtom)

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathRotateAtom_initWithOrgScilabForgeJlatexmathAtom_withNSString_withNSString_(OrgScilabForgeJlatexmathRotateAtom *self, OrgScilabForgeJlatexmathAtom *base, NSString *angle, NSString *option);

FOUNDATION_EXPORT OrgScilabForgeJlatexmathRotateAtom *new_OrgScilabForgeJlatexmathRotateAtom_initWithOrgScilabForgeJlatexmathAtom_withNSString_withNSString_(OrgScilabForgeJlatexmathAtom *base, NSString *angle, NSString *option) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathRotateAtom_initWithOrgScilabForgeJlatexmathAtom_withDouble_withNSString_(OrgScilabForgeJlatexmathRotateAtom *self, OrgScilabForgeJlatexmathAtom *base, jdouble angle, NSString *option);

FOUNDATION_EXPORT OrgScilabForgeJlatexmathRotateAtom *new_OrgScilabForgeJlatexmathRotateAtom_initWithOrgScilabForgeJlatexmathAtom_withDouble_withNSString_(OrgScilabForgeJlatexmathAtom *base, jdouble angle, NSString *option) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgScilabForgeJlatexmathRotateAtom)

#endif // _OrgScilabForgeJlatexmathRotateAtom_H_
