//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/scilab/forge/jlatexmath/Row.java
//

#ifndef _OrgScilabForgeJlatexmathRow_H_
#define _OrgScilabForgeJlatexmathRow_H_

#include "J2ObjC_header.h"

@class OrgScilabForgeJlatexmathDummy;

@protocol OrgScilabForgeJlatexmathRow < NSObject, JavaObject >

- (void)setPreviousAtomWithOrgScilabForgeJlatexmathDummy:(OrgScilabForgeJlatexmathDummy *)dummy;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgScilabForgeJlatexmathRow)

J2OBJC_TYPE_LITERAL_HEADER(OrgScilabForgeJlatexmathRow)

#endif // _OrgScilabForgeJlatexmathRow_H_
