//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/scilab/forge/jlatexmath/ShadowAtom.java
//


#include "Atom.h"
#include "Box.h"
#include "FBoxAtom.h"
#include "FramedBox.h"
#include "J2ObjC_source.h"
#include "ShadowAtom.h"
#include "ShadowBox.h"
#include "TeXEnvironment.h"
#include "TeXFont.h"

@implementation OrgScilabForgeJlatexmathShadowAtom

- (instancetype)initWithOrgScilabForgeJlatexmathAtom:(OrgScilabForgeJlatexmathAtom *)base {
  OrgScilabForgeJlatexmathShadowAtom_initWithOrgScilabForgeJlatexmathAtom_(self, base);
  return self;
}

- (OrgScilabForgeJlatexmathBox *)createBoxWithOrgScilabForgeJlatexmathTeXEnvironment:(OrgScilabForgeJlatexmathTeXEnvironment *)env {
  return new_OrgScilabForgeJlatexmathShadowBox_initWithOrgScilabForgeJlatexmathFramedBox_withFloat_((OrgScilabForgeJlatexmathFramedBox *) check_class_cast([super createBoxWithOrgScilabForgeJlatexmathTeXEnvironment:env], [OrgScilabForgeJlatexmathFramedBox class]), [((id<OrgScilabForgeJlatexmathTeXFont>) nil_chk([((OrgScilabForgeJlatexmathTeXEnvironment *) nil_chk(env)) getTeXFont])) getDefaultRuleThicknessWithInt:[env getStyle]] * 4);
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithOrgScilabForgeJlatexmathAtom:", "ShadowAtom", NULL, 0x1, NULL, NULL },
    { "createBoxWithOrgScilabForgeJlatexmathTeXEnvironment:", "createBox", "Lorg.scilab.forge.jlatexmath.Box;", 0x1, NULL, NULL },
  };
  static const J2ObjcClassInfo _OrgScilabForgeJlatexmathShadowAtom = { 2, "ShadowAtom", "org.scilab.forge.jlatexmath", NULL, 0x1, 2, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgScilabForgeJlatexmathShadowAtom;
}

@end

void OrgScilabForgeJlatexmathShadowAtom_initWithOrgScilabForgeJlatexmathAtom_(OrgScilabForgeJlatexmathShadowAtom *self, OrgScilabForgeJlatexmathAtom *base) {
  (void) OrgScilabForgeJlatexmathFBoxAtom_initWithOrgScilabForgeJlatexmathAtom_(self, base);
}

OrgScilabForgeJlatexmathShadowAtom *new_OrgScilabForgeJlatexmathShadowAtom_initWithOrgScilabForgeJlatexmathAtom_(OrgScilabForgeJlatexmathAtom *base) {
  OrgScilabForgeJlatexmathShadowAtom *self = [OrgScilabForgeJlatexmathShadowAtom alloc];
  OrgScilabForgeJlatexmathShadowAtom_initWithOrgScilabForgeJlatexmathAtom_(self, base);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgScilabForgeJlatexmathShadowAtom)
