//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/scilab/forge/jlatexmath/TeXConstants.java
//


#include "J2ObjC_source.h"
#include "TeXConstants.h"
#include "java/lang/Integer.h"
#include "java/util/HashMap.h"
#include "java/util/Map.h"

J2OBJC_INITIALIZED_DEFN(OrgScilabForgeJlatexmathTeXConstants)

id<JavaUtilMap> OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_;

@implementation OrgScilabForgeJlatexmathTeXConstants

- (instancetype)init {
  OrgScilabForgeJlatexmathTeXConstants_init(self);
  return self;
}

+ (void)initialize {
  if (self == [OrgScilabForgeJlatexmathTeXConstants class]) {
    OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ = new_JavaUtilHashMap_init();
    {
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"ALIGN_LEFT" withId:JavaLangInteger_valueOfWithInt_(0)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"ALIGN_RIGHT" withId:JavaLangInteger_valueOfWithInt_(1)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"ALIGN_CENTER" withId:JavaLangInteger_valueOfWithInt_(2)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"ALIGN_TOP" withId:JavaLangInteger_valueOfWithInt_(3)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"ALIGN_BOTTOM" withId:JavaLangInteger_valueOfWithInt_(4)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"ALIGN_NONE" withId:JavaLangInteger_valueOfWithInt_(5)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"THINMUSKIP" withId:JavaLangInteger_valueOfWithInt_(1)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"MEDMUSKIP" withId:JavaLangInteger_valueOfWithInt_(2)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"THICKMUSKIP" withId:JavaLangInteger_valueOfWithInt_(3)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"NEGTHINMUSKIP" withId:JavaLangInteger_valueOfWithInt_(-1)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"NEGMEDMUSKIP" withId:JavaLangInteger_valueOfWithInt_(-2)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"NEGTHICKMUSKIP" withId:JavaLangInteger_valueOfWithInt_(-3)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"QUAD" withId:JavaLangInteger_valueOfWithInt_(3)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"SCRIPT_NORMAL" withId:JavaLangInteger_valueOfWithInt_(0)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"SCRIPT_NOLIMITS" withId:JavaLangInteger_valueOfWithInt_(1)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"SCRIPT_LIMITS" withId:JavaLangInteger_valueOfWithInt_(2)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"TYPE_ORDINARY" withId:JavaLangInteger_valueOfWithInt_(0)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"TYPE_BIG_OPERATOR" withId:JavaLangInteger_valueOfWithInt_(1)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"TYPE_BINARY_OPERATOR" withId:JavaLangInteger_valueOfWithInt_(2)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"TYPE_RELATION" withId:JavaLangInteger_valueOfWithInt_(3)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"TYPE_OPENING" withId:JavaLangInteger_valueOfWithInt_(4)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"TYPE_CLOSING" withId:JavaLangInteger_valueOfWithInt_(5)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"TYPE_PUNCTUATION" withId:JavaLangInteger_valueOfWithInt_(6)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"TYPE_INNER" withId:JavaLangInteger_valueOfWithInt_(7)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"TYPE_ACCENT" withId:JavaLangInteger_valueOfWithInt_(10)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"TYPE_INTERTEXT" withId:JavaLangInteger_valueOfWithInt_(11)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"TYPE_MULTICOLUMN" withId:JavaLangInteger_valueOfWithInt_(12)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"TYPE_HLINE" withId:JavaLangInteger_valueOfWithInt_(13)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"DELIM_BRACE" withId:JavaLangInteger_valueOfWithInt_(0)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"DELIM_SQUARE_BRACKET" withId:JavaLangInteger_valueOfWithInt_(1)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"DELIM_BRACKET" withId:JavaLangInteger_valueOfWithInt_(2)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"DELIM_LEFT_ARROW" withId:JavaLangInteger_valueOfWithInt_(3)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"DELIM_RIGHT_ARROW" withId:JavaLangInteger_valueOfWithInt_(4)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"DELIM_LEFT_RIGHT_ARROW" withId:JavaLangInteger_valueOfWithInt_(5)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"DELIM_DOUBLE_LEFT_ARROW" withId:JavaLangInteger_valueOfWithInt_(6)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"DELIM_DOUBLE_RIGHT_ARROW" withId:JavaLangInteger_valueOfWithInt_(7)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"DELIM_DOUBLE_LEFT_RIGHT_ARROW" withId:JavaLangInteger_valueOfWithInt_(8)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"DELIM_SINGLE_LINE" withId:JavaLangInteger_valueOfWithInt_(9)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"DELIM_DOUBLE_LINE" withId:JavaLangInteger_valueOfWithInt_(10)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"STYLE_DISPLAY" withId:JavaLangInteger_valueOfWithInt_(0)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"STYLE_TEXT" withId:JavaLangInteger_valueOfWithInt_(2)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"STYLE_SCRIPT" withId:JavaLangInteger_valueOfWithInt_(4)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"STYLE_SCRIPT_SCRIPT" withId:JavaLangInteger_valueOfWithInt_(6)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"UNIT_EM" withId:JavaLangInteger_valueOfWithInt_(0)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"UNIT_EX" withId:JavaLangInteger_valueOfWithInt_(1)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"UNIT_PIXEL" withId:JavaLangInteger_valueOfWithInt_(2)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"UNIT_POINT" withId:JavaLangInteger_valueOfWithInt_(3)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"UNIT_PICA" withId:JavaLangInteger_valueOfWithInt_(4)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"UNIT_MU" withId:JavaLangInteger_valueOfWithInt_(5)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"UNIT_CM" withId:JavaLangInteger_valueOfWithInt_(6)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"UNIT_MM" withId:JavaLangInteger_valueOfWithInt_(7)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"UNIT_IN" withId:JavaLangInteger_valueOfWithInt_(8)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"UNIT_SP" withId:JavaLangInteger_valueOfWithInt_(9)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"UNIT_PT" withId:JavaLangInteger_valueOfWithInt_(10)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"UNIT_DD" withId:JavaLangInteger_valueOfWithInt_(11)];
      (void) [OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_ putWithId:@"UNIT_CC" withId:JavaLangInteger_valueOfWithInt_(12)];
    }
    J2OBJC_SET_INITIALIZED(OrgScilabForgeJlatexmathTeXConstants)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "ALIGN_LEFT_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_ALIGN_LEFT },
    { "ALIGN_RIGHT_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_ALIGN_RIGHT },
    { "ALIGN_CENTER_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_ALIGN_CENTER },
    { "ALIGN_TOP_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_ALIGN_TOP },
    { "ALIGN_BOTTOM_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_ALIGN_BOTTOM },
    { "ALIGN_NONE_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_ALIGN_NONE },
    { "THINMUSKIP_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_THINMUSKIP },
    { "MEDMUSKIP_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_MEDMUSKIP },
    { "THICKMUSKIP_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_THICKMUSKIP },
    { "NEGTHINMUSKIP_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_NEGTHINMUSKIP },
    { "NEGMEDMUSKIP_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_NEGMEDMUSKIP },
    { "NEGTHICKMUSKIP_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_NEGTHICKMUSKIP },
    { "QUAD_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_QUAD },
    { "SCRIPT_NORMAL_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_SCRIPT_NORMAL },
    { "SCRIPT_NOLIMITS_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_SCRIPT_NOLIMITS },
    { "SCRIPT_LIMITS_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_SCRIPT_LIMITS },
    { "TYPE_ORDINARY_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_TYPE_ORDINARY },
    { "TYPE_BIG_OPERATOR_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_TYPE_BIG_OPERATOR },
    { "TYPE_BINARY_OPERATOR_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_TYPE_BINARY_OPERATOR },
    { "TYPE_RELATION_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_TYPE_RELATION },
    { "TYPE_OPENING_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_TYPE_OPENING },
    { "TYPE_CLOSING_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_TYPE_CLOSING },
    { "TYPE_PUNCTUATION_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_TYPE_PUNCTUATION },
    { "TYPE_INNER_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_TYPE_INNER },
    { "TYPE_ACCENT_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_TYPE_ACCENT },
    { "TYPE_INTERTEXT_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_TYPE_INTERTEXT },
    { "TYPE_MULTICOLUMN_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_TYPE_MULTICOLUMN },
    { "TYPE_HLINE_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_TYPE_HLINE },
    { "DELIM_BRACE_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_DELIM_BRACE },
    { "DELIM_SQUARE_BRACKET_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_DELIM_SQUARE_BRACKET },
    { "DELIM_BRACKET_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_DELIM_BRACKET },
    { "DELIM_LEFT_ARROW_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_DELIM_LEFT_ARROW },
    { "DELIM_RIGHT_ARROW_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_DELIM_RIGHT_ARROW },
    { "DELIM_LEFT_RIGHT_ARROW_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_DELIM_LEFT_RIGHT_ARROW },
    { "DELIM_DOUBLE_LEFT_ARROW_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_DELIM_DOUBLE_LEFT_ARROW },
    { "DELIM_DOUBLE_RIGHT_ARROW_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_DELIM_DOUBLE_RIGHT_ARROW },
    { "DELIM_DOUBLE_LEFT_RIGHT_ARROW_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_DELIM_DOUBLE_LEFT_RIGHT_ARROW },
    { "DELIM_SINGLE_LINE_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_DELIM_SINGLE_LINE },
    { "DELIM_DOUBLE_LINE_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_DELIM_DOUBLE_LINE },
    { "STYLE_DISPLAY_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_STYLE_DISPLAY },
    { "STYLE_TEXT_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_STYLE_TEXT },
    { "STYLE_SCRIPT_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_STYLE_SCRIPT },
    { "STYLE_SCRIPT_SCRIPT_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_STYLE_SCRIPT_SCRIPT },
    { "UNIT_EM_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_UNIT_EM },
    { "UNIT_EX_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_UNIT_EX },
    { "UNIT_PIXEL_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_UNIT_PIXEL },
    { "UNIT_POINT_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_UNIT_POINT },
    { "UNIT_PICA_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_UNIT_PICA },
    { "UNIT_MU_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_UNIT_MU },
    { "UNIT_CM_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_UNIT_CM },
    { "UNIT_MM_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_UNIT_MM },
    { "UNIT_IN_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_UNIT_IN },
    { "UNIT_SP_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_UNIT_SP },
    { "UNIT_PT_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_UNIT_PT },
    { "UNIT_DD_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_UNIT_DD },
    { "UNIT_CC_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = OrgScilabForgeJlatexmathTeXConstants_UNIT_CC },
    { "CONSTANTS_MAP_", NULL, 0x19, "Ljava.util.Map;", &OrgScilabForgeJlatexmathTeXConstants_CONSTANTS_MAP_, "Ljava/util/Map<Ljava/lang/String;Ljava/lang/Integer;>;",  },
  };
  static const J2ObjcClassInfo _OrgScilabForgeJlatexmathTeXConstants = { 2, "TeXConstants", "org.scilab.forge.jlatexmath", NULL, 0x1, 1, methods, 57, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgScilabForgeJlatexmathTeXConstants;
}

@end

void OrgScilabForgeJlatexmathTeXConstants_init(OrgScilabForgeJlatexmathTeXConstants *self) {
  (void) NSObject_init(self);
}

OrgScilabForgeJlatexmathTeXConstants *new_OrgScilabForgeJlatexmathTeXConstants_init() {
  OrgScilabForgeJlatexmathTeXConstants *self = [OrgScilabForgeJlatexmathTeXConstants alloc];
  OrgScilabForgeJlatexmathTeXConstants_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgScilabForgeJlatexmathTeXConstants)
