//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/scilab/forge/jlatexmath/UnderOverAtom.java
//

#ifndef _OrgScilabForgeJlatexmathUnderOverAtom_H_
#define _OrgScilabForgeJlatexmathUnderOverAtom_H_

#include "Atom.h"
#include "J2ObjC_header.h"

@class OrgScilabForgeJlatexmathBox;
@class OrgScilabForgeJlatexmathTeXEnvironment;

@interface OrgScilabForgeJlatexmathUnderOverAtom : OrgScilabForgeJlatexmathAtom

#pragma mark Public

- (instancetype)initWithOrgScilabForgeJlatexmathAtom:(OrgScilabForgeJlatexmathAtom *)base
                    withOrgScilabForgeJlatexmathAtom:(OrgScilabForgeJlatexmathAtom *)under
                                             withInt:(jint)underUnit
                                           withFloat:(jfloat)underSpace
                                         withBoolean:(jboolean)underScriptSize
                    withOrgScilabForgeJlatexmathAtom:(OrgScilabForgeJlatexmathAtom *)over
                                             withInt:(jint)overUnit
                                           withFloat:(jfloat)overSpace
                                         withBoolean:(jboolean)overScriptSize;

- (instancetype)initWithOrgScilabForgeJlatexmathAtom:(OrgScilabForgeJlatexmathAtom *)base
                    withOrgScilabForgeJlatexmathAtom:(OrgScilabForgeJlatexmathAtom *)underOver
                                             withInt:(jint)underOverUnit
                                           withFloat:(jfloat)underOverSpace
                                         withBoolean:(jboolean)underOverScriptSize
                                         withBoolean:(jboolean)over;

- (OrgScilabForgeJlatexmathBox *)createBoxWithOrgScilabForgeJlatexmathTeXEnvironment:(OrgScilabForgeJlatexmathTeXEnvironment *)env;

- (jint)getLeftType;

- (jint)getRightType;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgScilabForgeJlatexmathUnderOverAtom)

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathUnderOverAtom_initWithOrgScilabForgeJlatexmathAtom_withOrgScilabForgeJlatexmathAtom_withInt_withFloat_withBoolean_withBoolean_(OrgScilabForgeJlatexmathUnderOverAtom *self, OrgScilabForgeJlatexmathAtom *base, OrgScilabForgeJlatexmathAtom *underOver, jint underOverUnit, jfloat underOverSpace, jboolean underOverScriptSize, jboolean over);

FOUNDATION_EXPORT OrgScilabForgeJlatexmathUnderOverAtom *new_OrgScilabForgeJlatexmathUnderOverAtom_initWithOrgScilabForgeJlatexmathAtom_withOrgScilabForgeJlatexmathAtom_withInt_withFloat_withBoolean_withBoolean_(OrgScilabForgeJlatexmathAtom *base, OrgScilabForgeJlatexmathAtom *underOver, jint underOverUnit, jfloat underOverSpace, jboolean underOverScriptSize, jboolean over) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathUnderOverAtom_initWithOrgScilabForgeJlatexmathAtom_withOrgScilabForgeJlatexmathAtom_withInt_withFloat_withBoolean_withOrgScilabForgeJlatexmathAtom_withInt_withFloat_withBoolean_(OrgScilabForgeJlatexmathUnderOverAtom *self, OrgScilabForgeJlatexmathAtom *base, OrgScilabForgeJlatexmathAtom *under, jint underUnit, jfloat underSpace, jboolean underScriptSize, OrgScilabForgeJlatexmathAtom *over, jint overUnit, jfloat overSpace, jboolean overScriptSize);

FOUNDATION_EXPORT OrgScilabForgeJlatexmathUnderOverAtom *new_OrgScilabForgeJlatexmathUnderOverAtom_initWithOrgScilabForgeJlatexmathAtom_withOrgScilabForgeJlatexmathAtom_withInt_withFloat_withBoolean_withOrgScilabForgeJlatexmathAtom_withInt_withFloat_withBoolean_(OrgScilabForgeJlatexmathAtom *base, OrgScilabForgeJlatexmathAtom *under, jint underUnit, jfloat underSpace, jboolean underScriptSize, OrgScilabForgeJlatexmathAtom *over, jint overUnit, jfloat overSpace, jboolean overScriptSize) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgScilabForgeJlatexmathUnderOverAtom)

#endif // _OrgScilabForgeJlatexmathUnderOverAtom_H_
