//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/scilab/forge/jlatexmath/XArrowAtom.java
//

#ifndef _OrgScilabForgeJlatexmathXArrowAtom_H_
#define _OrgScilabForgeJlatexmathXArrowAtom_H_

#include "Atom.h"
#include "J2ObjC_header.h"

@class OrgScilabForgeJlatexmathBox;
@class OrgScilabForgeJlatexmathTeXEnvironment;

@interface OrgScilabForgeJlatexmathXArrowAtom : OrgScilabForgeJlatexmathAtom

#pragma mark Public

- (instancetype)initWithOrgScilabForgeJlatexmathAtom:(OrgScilabForgeJlatexmathAtom *)over
                    withOrgScilabForgeJlatexmathAtom:(OrgScilabForgeJlatexmathAtom *)under
                                         withBoolean:(jboolean)left;

- (OrgScilabForgeJlatexmathBox *)createBoxWithOrgScilabForgeJlatexmathTeXEnvironment:(OrgScilabForgeJlatexmathTeXEnvironment *)env;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgScilabForgeJlatexmathXArrowAtom)

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathXArrowAtom_initWithOrgScilabForgeJlatexmathAtom_withOrgScilabForgeJlatexmathAtom_withBoolean_(OrgScilabForgeJlatexmathXArrowAtom *self, OrgScilabForgeJlatexmathAtom *over, OrgScilabForgeJlatexmathAtom *under, jboolean left);

FOUNDATION_EXPORT OrgScilabForgeJlatexmathXArrowAtom *new_OrgScilabForgeJlatexmathXArrowAtom_initWithOrgScilabForgeJlatexmathAtom_withOrgScilabForgeJlatexmathAtom_withBoolean_(OrgScilabForgeJlatexmathAtom *over, OrgScilabForgeJlatexmathAtom *under, jboolean left) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgScilabForgeJlatexmathXArrowAtom)

#endif // _OrgScilabForgeJlatexmathXArrowAtom_H_
