//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/GeoGebraiOSARC/GeoGebraiOSARC/javasources/org/scilab/forge/jlatexmath/exception/XMLResourceParseException.java
//

#ifndef _OrgScilabForgeJlatexmathExceptionXMLResourceParseException_H_
#define _OrgScilabForgeJlatexmathExceptionXMLResourceParseException_H_

#include "J2ObjC_header.h"
#include "ResourceParseException.h"

@class JavaLangThrowable;

@interface OrgScilabForgeJlatexmathExceptionXMLResourceParseException : OrgScilabForgeJlatexmathExceptionResourceParseException

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)msg;

- (instancetype)initWithNSString:(NSString *)resourceName
                    withNSString:(NSString *)elementName;

- (instancetype)initWithNSString:(NSString *)resourceName
                    withNSString:(NSString *)elementName
                    withNSString:(NSString *)attributeName
                    withNSString:(NSString *)msg;

- (instancetype)initWithNSString:(NSString *)resourceName
                    withNSString:(NSString *)elementName
                    withNSString:(NSString *)attributeName
                    withNSString:(NSString *)msg
           withJavaLangThrowable:(JavaLangThrowable *)e;

- (instancetype)initWithNSString:(NSString *)resourceName
           withJavaLangThrowable:(JavaLangThrowable *)e;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgScilabForgeJlatexmathExceptionXMLResourceParseException)

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathExceptionXMLResourceParseException_initWithNSString_withNSString_withNSString_withNSString_(OrgScilabForgeJlatexmathExceptionXMLResourceParseException *self, NSString *resourceName, NSString *elementName, NSString *attributeName, NSString *msg);

FOUNDATION_EXPORT OrgScilabForgeJlatexmathExceptionXMLResourceParseException *new_OrgScilabForgeJlatexmathExceptionXMLResourceParseException_initWithNSString_withNSString_withNSString_withNSString_(NSString *resourceName, NSString *elementName, NSString *attributeName, NSString *msg) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathExceptionXMLResourceParseException_initWithNSString_withNSString_withNSString_withNSString_withJavaLangThrowable_(OrgScilabForgeJlatexmathExceptionXMLResourceParseException *self, NSString *resourceName, NSString *elementName, NSString *attributeName, NSString *msg, JavaLangThrowable *e);

FOUNDATION_EXPORT OrgScilabForgeJlatexmathExceptionXMLResourceParseException *new_OrgScilabForgeJlatexmathExceptionXMLResourceParseException_initWithNSString_withNSString_withNSString_withNSString_withJavaLangThrowable_(NSString *resourceName, NSString *elementName, NSString *attributeName, NSString *msg, JavaLangThrowable *e) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathExceptionXMLResourceParseException_initWithNSString_withNSString_(OrgScilabForgeJlatexmathExceptionXMLResourceParseException *self, NSString *resourceName, NSString *elementName);

FOUNDATION_EXPORT OrgScilabForgeJlatexmathExceptionXMLResourceParseException *new_OrgScilabForgeJlatexmathExceptionXMLResourceParseException_initWithNSString_withNSString_(NSString *resourceName, NSString *elementName) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathExceptionXMLResourceParseException_initWithNSString_withJavaLangThrowable_(OrgScilabForgeJlatexmathExceptionXMLResourceParseException *self, NSString *resourceName, JavaLangThrowable *e);

FOUNDATION_EXPORT OrgScilabForgeJlatexmathExceptionXMLResourceParseException *new_OrgScilabForgeJlatexmathExceptionXMLResourceParseException_initWithNSString_withJavaLangThrowable_(NSString *resourceName, JavaLangThrowable *e) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathExceptionXMLResourceParseException_initWithNSString_(OrgScilabForgeJlatexmathExceptionXMLResourceParseException *self, NSString *msg);

FOUNDATION_EXPORT OrgScilabForgeJlatexmathExceptionXMLResourceParseException *new_OrgScilabForgeJlatexmathExceptionXMLResourceParseException_initWithNSString_(NSString *msg) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgScilabForgeJlatexmathExceptionXMLResourceParseException)

#endif // _OrgScilabForgeJlatexmathExceptionXMLResourceParseException_H_
