//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/JLaTeXMath-iOS/JLaTeXMath-iOS/jlatexmath-share/org/scilab/forge/jlatexmath/CharBox.java
//


#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "org/scilab/forge/jlatexmath/Box.h"
#include "org/scilab/forge/jlatexmath/Char.h"
#include "org/scilab/forge/jlatexmath/CharBox.h"
#include "org/scilab/forge/jlatexmath/CharFont.h"
#include "org/scilab/forge/jlatexmath/FontInfo.h"
#include "org/scilab/forge/jlatexmath/Metrics.h"
#include "org/scilab/forge/jlatexmath/platform/font/Font.h"
#include "org/scilab/forge/jlatexmath/platform/graphics/Graphics2DInterface.h"

@interface OrgScilabForgeJlatexmathCharBox () {
 @public
  OrgScilabForgeJlatexmathCharFont *cf_;
  jfloat size_;
  IOSCharArray *arr_;
}

@end

J2OBJC_FIELD_SETTER(OrgScilabForgeJlatexmathCharBox, cf_, OrgScilabForgeJlatexmathCharFont *)
J2OBJC_FIELD_SETTER(OrgScilabForgeJlatexmathCharBox, arr_, IOSCharArray *)

@implementation OrgScilabForgeJlatexmathCharBox

- (instancetype)initWithOrgScilabForgeJlatexmathChar:(OrgScilabForgeJlatexmathChar *)c {
  OrgScilabForgeJlatexmathCharBox_initWithOrgScilabForgeJlatexmathChar_(self, c);
  return self;
}

- (void)drawWithOrgScilabForgeJlatexmathPlatformGraphicsGraphics2DInterface:(id<OrgScilabForgeJlatexmathPlatformGraphicsGraphics2DInterface>)g2
                                                                  withFloat:(jfloat)x
                                                                  withFloat:(jfloat)y {
  [self drawDebugWithOrgScilabForgeJlatexmathPlatformGraphicsGraphics2DInterface:g2 withFloat:x withFloat:y];
  [((id<OrgScilabForgeJlatexmathPlatformGraphicsGraphics2DInterface>) nil_chk(g2)) saveTransformation];
  [g2 translateWithDouble:x withDouble:y];
  id<OrgScilabForgeJlatexmathPlatformFontFont> font = OrgScilabForgeJlatexmathFontInfo_getFontWithInt_(((OrgScilabForgeJlatexmathCharFont *) nil_chk(cf_))->fontId_);
  if (size_ != 1) {
    [g2 scale__WithDouble:size_ withDouble:size_];
  }
  if ([g2 getFont] != font) {
    [g2 setFontWithOrgScilabForgeJlatexmathPlatformFontFont:font];
  }
  *IOSCharArray_GetRef(nil_chk(arr_), 0) = cf_->c_;
  [g2 drawCharsWithCharArray:arr_ withInt:0 withInt:1 withInt:0 withInt:0];
  [g2 restoreTransformation];
}

- (jint)getLastFontId {
  return ((OrgScilabForgeJlatexmathCharFont *) nil_chk(cf_))->fontId_;
}

- (NSString *)description {
  return JreStrcat("$CC", [super description], '=', ((OrgScilabForgeJlatexmathCharFont *) nil_chk(cf_))->c_);
}

- (void)dealloc {
  RELEASE_(cf_);
  RELEASE_(arr_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithOrgScilabForgeJlatexmathChar:", "CharBox", NULL, 0x1, NULL, NULL },
    { "drawWithOrgScilabForgeJlatexmathPlatformGraphicsGraphics2DInterface:withFloat:withFloat:", "draw", "V", 0x1, NULL, NULL },
    { "getLastFontId", NULL, "I", 0x1, NULL, NULL },
    { "description", "toString", "Ljava.lang.String;", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "cf_", NULL, 0x12, "Lorg.scilab.forge.jlatexmath.CharFont;", NULL, NULL,  },
    { "size_", NULL, 0x12, "F", NULL, NULL,  },
    { "arr_", NULL, 0x12, "[C", NULL, NULL,  },
  };
  static const J2ObjcClassInfo _OrgScilabForgeJlatexmathCharBox = { 2, "CharBox", "org.scilab.forge.jlatexmath", NULL, 0x1, 4, methods, 3, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgScilabForgeJlatexmathCharBox;
}

@end

void OrgScilabForgeJlatexmathCharBox_initWithOrgScilabForgeJlatexmathChar_(OrgScilabForgeJlatexmathCharBox *self, OrgScilabForgeJlatexmathChar *c) {
  OrgScilabForgeJlatexmathBox_init(self);
  OrgScilabForgeJlatexmathCharBox_setAndConsume_arr_(self, [IOSCharArray newArrayWithLength:1]);
  OrgScilabForgeJlatexmathCharBox_set_cf_(self, [((OrgScilabForgeJlatexmathChar *) nil_chk(c)) getCharFont]);
  self->size_ = [((OrgScilabForgeJlatexmathMetrics *) nil_chk([c getMetrics])) getSize];
  self->width_ = [c getWidth];
  self->height_ = [c getHeight];
  self->depth_ = [c getDepth];
}

OrgScilabForgeJlatexmathCharBox *new_OrgScilabForgeJlatexmathCharBox_initWithOrgScilabForgeJlatexmathChar_(OrgScilabForgeJlatexmathChar *c) {
  OrgScilabForgeJlatexmathCharBox *self = [OrgScilabForgeJlatexmathCharBox alloc];
  OrgScilabForgeJlatexmathCharBox_initWithOrgScilabForgeJlatexmathChar_(self, c);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgScilabForgeJlatexmathCharBox)
