//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/JLaTeXMath-iOS/JLaTeXMath-iOS/jlatexmath-share/org/scilab/forge/jlatexmath/CharFont.java
//


#include "J2ObjC_source.h"
#include "org/scilab/forge/jlatexmath/CharFont.h"

@implementation OrgScilabForgeJlatexmathCharFont

- (instancetype)initWithChar:(jchar)ch
                     withInt:(jint)f {
  OrgScilabForgeJlatexmathCharFont_initWithChar_withInt_(self, ch, f);
  return self;
}

- (instancetype)initWithChar:(jchar)ch
                     withInt:(jint)f
                     withInt:(jint)bf {
  OrgScilabForgeJlatexmathCharFont_initWithChar_withInt_withInt_(self, ch, f, bf);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithChar:withInt:", "CharFont", NULL, 0x1, NULL, NULL },
    { "initWithChar:withInt:withInt:", "CharFont", NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "c_", NULL, 0x1, "C", NULL, NULL,  },
    { "fontId_", NULL, 0x1, "I", NULL, NULL,  },
    { "boldFontId_", NULL, 0x1, "I", NULL, NULL,  },
  };
  static const J2ObjcClassInfo _OrgScilabForgeJlatexmathCharFont = { 2, "CharFont", "org.scilab.forge.jlatexmath", NULL, 0x1, 2, methods, 3, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgScilabForgeJlatexmathCharFont;
}

@end

void OrgScilabForgeJlatexmathCharFont_initWithChar_withInt_(OrgScilabForgeJlatexmathCharFont *self, jchar ch, jint f) {
  OrgScilabForgeJlatexmathCharFont_initWithChar_withInt_withInt_(self, ch, f, f);
}

OrgScilabForgeJlatexmathCharFont *new_OrgScilabForgeJlatexmathCharFont_initWithChar_withInt_(jchar ch, jint f) {
  OrgScilabForgeJlatexmathCharFont *self = [OrgScilabForgeJlatexmathCharFont alloc];
  OrgScilabForgeJlatexmathCharFont_initWithChar_withInt_(self, ch, f);
  return self;
}

void OrgScilabForgeJlatexmathCharFont_initWithChar_withInt_withInt_(OrgScilabForgeJlatexmathCharFont *self, jchar ch, jint f, jint bf) {
  NSObject_init(self);
  self->c_ = ch;
  self->fontId_ = f;
  self->boldFontId_ = bf;
}

OrgScilabForgeJlatexmathCharFont *new_OrgScilabForgeJlatexmathCharFont_initWithChar_withInt_withInt_(jchar ch, jint f, jint bf) {
  OrgScilabForgeJlatexmathCharFont *self = [OrgScilabForgeJlatexmathCharFont alloc];
  OrgScilabForgeJlatexmathCharFont_initWithChar_withInt_withInt_(self, ch, f, bf);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgScilabForgeJlatexmathCharFont)
