//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/JLaTeXMath-iOS/JLaTeXMath-iOS/jlatexmath-share/org/scilab/forge/jlatexmath/DefaultTeXFont.java
//

#ifndef _OrgScilabForgeJlatexmathDefaultTeXFont_H_
#define _OrgScilabForgeJlatexmathDefaultTeXFont_H_

#include "J2ObjC_header.h"
#include "org/scilab/forge/jlatexmath/TeXFont.h"

@class IOSObjectArray;
@class OrgScilabForgeJlatexmathChar;
@class OrgScilabForgeJlatexmathCharFont;
@class OrgScilabForgeJlatexmathCharacterCharacter_UnicodeBlock;
@class OrgScilabForgeJlatexmathExtension;
@protocol JavaUtilList;
@protocol JavaUtilMap;
@protocol OrgScilabForgeJlatexmathAlphabetRegistration;

#define OrgScilabForgeJlatexmathDefaultTeXFont_NONE -1
#define OrgScilabForgeJlatexmathDefaultTeXFont_NUMBERS 0
#define OrgScilabForgeJlatexmathDefaultTeXFont_CAPITALS 1
#define OrgScilabForgeJlatexmathDefaultTeXFont_SMALL 2
#define OrgScilabForgeJlatexmathDefaultTeXFont_UNICODE 3
#define OrgScilabForgeJlatexmathDefaultTeXFont_TOP 0
#define OrgScilabForgeJlatexmathDefaultTeXFont_MID 1
#define OrgScilabForgeJlatexmathDefaultTeXFont_REP 2
#define OrgScilabForgeJlatexmathDefaultTeXFont_BOT 3
#define OrgScilabForgeJlatexmathDefaultTeXFont_WIDTH 0
#define OrgScilabForgeJlatexmathDefaultTeXFont_HEIGHT 1
#define OrgScilabForgeJlatexmathDefaultTeXFont_DEPTH 2
#define OrgScilabForgeJlatexmathDefaultTeXFont_IT 3

@interface OrgScilabForgeJlatexmathDefaultTeXFont : NSObject < OrgScilabForgeJlatexmathTeXFont > {
 @public
  jfloat factor_;
  jboolean isBold_;
  jboolean isRoman_;
  jboolean isSs_;
  jboolean isTt_;
  jboolean isIt_;
}

#pragma mark Public

- (instancetype)initWithFloat:(jfloat)pointSize;

- (instancetype)initWithFloat:(jfloat)pointSize
                  withBoolean:(jboolean)b
                  withBoolean:(jboolean)rm
                  withBoolean:(jboolean)ss
                  withBoolean:(jboolean)tt
                  withBoolean:(jboolean)it;

- (instancetype)initWithFloat:(jfloat)pointSize
                    withFloat:(jfloat)f
                  withBoolean:(jboolean)b
                  withBoolean:(jboolean)rm
                  withBoolean:(jboolean)ss
                  withBoolean:(jboolean)tt
                  withBoolean:(jboolean)it;

+ (void)addAlphabetWithOrgScilabForgeJlatexmathAlphabetRegistration:(id<OrgScilabForgeJlatexmathAlphabetRegistration>)reg;

+ (void)addAlphabetWithId:(id)base
withOrgScilabForgeJlatexmathCharacterCharacter_UnicodeBlockArray:(IOSObjectArray *)alphabet
             withNSString:(NSString *)language;

+ (void)addAlphabetWithOrgScilabForgeJlatexmathCharacterCharacter_UnicodeBlock:(OrgScilabForgeJlatexmathCharacterCharacter_UnicodeBlock *)alphabet
                                                                        withId:(id)inlanguage
                                                                  withNSString:(NSString *)language
                                                                        withId:(id)insymbols
                                                                  withNSString:(NSString *)symbols
                                                                        withId:(id)inmappings
                                                                  withNSString:(NSString *)mappings;

+ (void)addAlphabetWithOrgScilabForgeJlatexmathCharacterCharacter_UnicodeBlock:(OrgScilabForgeJlatexmathCharacterCharacter_UnicodeBlock *)alphabet
                                                                  withNSString:(NSString *)name;

+ (void)addTeXFontDescriptionWithId:(id)base
                             withId:(id)inArg
                       withNSString:(NSString *)name;

+ (void)addTeXFontDescriptionWithId:(id)inArg
                       withNSString:(NSString *)name;

+ (void)addTeXFontDescriptionWithNSString:(NSString *)file;

- (id<OrgScilabForgeJlatexmathTeXFont>)copy__ OBJC_METHOD_FAMILY_NONE;

- (id<OrgScilabForgeJlatexmathTeXFont>)deriveFontWithFloat:(jfloat)size;

+ (void)enableMagnificationWithBoolean:(jboolean)b;

- (jfloat)getAxisHeightWithInt:(jint)style;

- (jfloat)getBigOpSpacing1WithInt:(jint)style;

- (jfloat)getBigOpSpacing2WithInt:(jint)style;

- (jfloat)getBigOpSpacing3WithInt:(jint)style;

- (jfloat)getBigOpSpacing4WithInt:(jint)style;

- (jfloat)getBigOpSpacing5WithInt:(jint)style;

- (jboolean)getBold;

- (OrgScilabForgeJlatexmathChar *)getCharWithChar:(jchar)c
                                     withNSString:(NSString *)textStyle
                                          withInt:(jint)style;

- (OrgScilabForgeJlatexmathChar *)getCharWithOrgScilabForgeJlatexmathCharFont:(OrgScilabForgeJlatexmathCharFont *)cf
                                                                      withInt:(jint)style;

- (OrgScilabForgeJlatexmathChar *)getCharWithNSString:(NSString *)symbolName
                                              withInt:(jint)style;

- (OrgScilabForgeJlatexmathChar *)getDefaultCharWithChar:(jchar)c
                                                 withInt:(jint)style;

- (jfloat)getDefaultRuleThicknessWithInt:(jint)style;

- (jfloat)getDenom1WithInt:(jint)style;

- (jfloat)getDenom2WithInt:(jint)style;

- (jfloat)getEMWithInt:(jint)style;

- (OrgScilabForgeJlatexmathExtension *)getExtensionWithOrgScilabForgeJlatexmathChar:(OrgScilabForgeJlatexmathChar *)c
                                                                            withInt:(jint)style;

- (jboolean)getIt;

- (jfloat)getKernWithOrgScilabForgeJlatexmathCharFont:(OrgScilabForgeJlatexmathCharFont *)left
                 withOrgScilabForgeJlatexmathCharFont:(OrgScilabForgeJlatexmathCharFont *)right
                                              withInt:(jint)style;

- (OrgScilabForgeJlatexmathCharFont *)getLigatureWithOrgScilabForgeJlatexmathCharFont:(OrgScilabForgeJlatexmathCharFont *)left
                                                 withOrgScilabForgeJlatexmathCharFont:(OrgScilabForgeJlatexmathCharFont *)right;

- (jint)getMuFontId;

- (OrgScilabForgeJlatexmathChar *)getNextLargerWithOrgScilabForgeJlatexmathChar:(OrgScilabForgeJlatexmathChar *)c
                                                                        withInt:(jint)style;

- (jfloat)getNum1WithInt:(jint)style;

- (jfloat)getNum2WithInt:(jint)style;

- (jfloat)getNum3WithInt:(jint)style;

- (jfloat)getQuadWithInt:(jint)style
                 withInt:(jint)fontCode;

- (jboolean)getRoman;

- (jfloat)getScaleFactor;

- (jfloat)getSize;

+ (jfloat)getSizeFactorWithInt:(jint)style;

- (jfloat)getSkewWithOrgScilabForgeJlatexmathCharFont:(OrgScilabForgeJlatexmathCharFont *)cf
                                              withInt:(jint)style;

- (jfloat)getSpaceWithInt:(jint)style;

- (jboolean)getSs;

- (jfloat)getSub1WithInt:(jint)style;

- (jfloat)getSub2WithInt:(jint)style;

- (jfloat)getSubDropWithInt:(jint)style;

- (jfloat)getSup1WithInt:(jint)style;

- (jfloat)getSup2WithInt:(jint)style;

- (jfloat)getSup3WithInt:(jint)style;

- (jfloat)getSupDropWithInt:(jint)style;

- (jboolean)getTt;

- (jfloat)getXHeightWithInt:(jint)style
                    withInt:(jint)fontCode;

- (jboolean)hasNextLargerWithOrgScilabForgeJlatexmathChar:(OrgScilabForgeJlatexmathChar *)c;

- (jboolean)hasSpaceWithInt:(jint)font;

- (jboolean)isExtensionCharWithOrgScilabForgeJlatexmathChar:(OrgScilabForgeJlatexmathChar *)c;

+ (void)registerAlphabetWithOrgScilabForgeJlatexmathAlphabetRegistration:(id<OrgScilabForgeJlatexmathAlphabetRegistration>)reg;

- (id<OrgScilabForgeJlatexmathTeXFont>)scaleFontWithFloat:(jfloat)factor;

- (void)setBoldWithBoolean:(jboolean)bold;

- (void)setItWithBoolean:(jboolean)it;

+ (void)setMagnificationWithFloat:(jfloat)mag;

+ (void)setMathSizesWithFloat:(jfloat)ds
                    withFloat:(jfloat)ts
                    withFloat:(jfloat)ss
                    withFloat:(jfloat)sss;

- (void)setRomanWithBoolean:(jboolean)rm;

- (void)setSsWithBoolean:(jboolean)ss;

- (void)setTtWithBoolean:(jboolean)tt;

@end

J2OBJC_STATIC_INIT(OrgScilabForgeJlatexmathDefaultTeXFont)

J2OBJC_STATIC_FIELD_GETTER(OrgScilabForgeJlatexmathDefaultTeXFont, NONE, jint)

J2OBJC_STATIC_FIELD_GETTER(OrgScilabForgeJlatexmathDefaultTeXFont, NUMBERS, jint)

J2OBJC_STATIC_FIELD_GETTER(OrgScilabForgeJlatexmathDefaultTeXFont, CAPITALS, jint)

J2OBJC_STATIC_FIELD_GETTER(OrgScilabForgeJlatexmathDefaultTeXFont, SMALL, jint)

J2OBJC_STATIC_FIELD_GETTER(OrgScilabForgeJlatexmathDefaultTeXFont, UNICODE, jint)

J2OBJC_STATIC_FIELD_GETTER(OrgScilabForgeJlatexmathDefaultTeXFont, TOP, jint)

J2OBJC_STATIC_FIELD_GETTER(OrgScilabForgeJlatexmathDefaultTeXFont, MID, jint)

J2OBJC_STATIC_FIELD_GETTER(OrgScilabForgeJlatexmathDefaultTeXFont, REP, jint)

J2OBJC_STATIC_FIELD_GETTER(OrgScilabForgeJlatexmathDefaultTeXFont, BOT, jint)

J2OBJC_STATIC_FIELD_GETTER(OrgScilabForgeJlatexmathDefaultTeXFont, WIDTH, jint)

J2OBJC_STATIC_FIELD_GETTER(OrgScilabForgeJlatexmathDefaultTeXFont, HEIGHT, jint)

J2OBJC_STATIC_FIELD_GETTER(OrgScilabForgeJlatexmathDefaultTeXFont, DEPTH, jint)

J2OBJC_STATIC_FIELD_GETTER(OrgScilabForgeJlatexmathDefaultTeXFont, IT, jint)

FOUNDATION_EXPORT id<JavaUtilList> OrgScilabForgeJlatexmathDefaultTeXFont_loadedAlphabets_;
J2OBJC_STATIC_FIELD_GETTER(OrgScilabForgeJlatexmathDefaultTeXFont, loadedAlphabets_, id<JavaUtilList>)
J2OBJC_STATIC_FIELD_SETTER(OrgScilabForgeJlatexmathDefaultTeXFont, loadedAlphabets_, id<JavaUtilList>)

FOUNDATION_EXPORT id<JavaUtilMap> OrgScilabForgeJlatexmathDefaultTeXFont_registeredAlphabets_;
J2OBJC_STATIC_FIELD_GETTER(OrgScilabForgeJlatexmathDefaultTeXFont, registeredAlphabets_, id<JavaUtilMap>)
J2OBJC_STATIC_FIELD_SETTER(OrgScilabForgeJlatexmathDefaultTeXFont, registeredAlphabets_, id<JavaUtilMap>)

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathDefaultTeXFont_initWithFloat_(OrgScilabForgeJlatexmathDefaultTeXFont *self, jfloat pointSize);

FOUNDATION_EXPORT OrgScilabForgeJlatexmathDefaultTeXFont *new_OrgScilabForgeJlatexmathDefaultTeXFont_initWithFloat_(jfloat pointSize) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathDefaultTeXFont_initWithFloat_withBoolean_withBoolean_withBoolean_withBoolean_withBoolean_(OrgScilabForgeJlatexmathDefaultTeXFont *self, jfloat pointSize, jboolean b, jboolean rm, jboolean ss, jboolean tt, jboolean it);

FOUNDATION_EXPORT OrgScilabForgeJlatexmathDefaultTeXFont *new_OrgScilabForgeJlatexmathDefaultTeXFont_initWithFloat_withBoolean_withBoolean_withBoolean_withBoolean_withBoolean_(jfloat pointSize, jboolean b, jboolean rm, jboolean ss, jboolean tt, jboolean it) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathDefaultTeXFont_initWithFloat_withFloat_withBoolean_withBoolean_withBoolean_withBoolean_withBoolean_(OrgScilabForgeJlatexmathDefaultTeXFont *self, jfloat pointSize, jfloat f, jboolean b, jboolean rm, jboolean ss, jboolean tt, jboolean it);

FOUNDATION_EXPORT OrgScilabForgeJlatexmathDefaultTeXFont *new_OrgScilabForgeJlatexmathDefaultTeXFont_initWithFloat_withFloat_withBoolean_withBoolean_withBoolean_withBoolean_withBoolean_(jfloat pointSize, jfloat f, jboolean b, jboolean rm, jboolean ss, jboolean tt, jboolean it) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathDefaultTeXFont_addTeXFontDescriptionWithNSString_(NSString *file);

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathDefaultTeXFont_addTeXFontDescriptionWithId_withNSString_(id inArg, NSString *name);

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathDefaultTeXFont_addTeXFontDescriptionWithId_withId_withNSString_(id base, id inArg, NSString *name);

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathDefaultTeXFont_addAlphabetWithOrgScilabForgeJlatexmathCharacterCharacter_UnicodeBlock_withId_withNSString_withId_withNSString_withId_withNSString_(OrgScilabForgeJlatexmathCharacterCharacter_UnicodeBlock *alphabet, id inlanguage, NSString *language, id insymbols, NSString *symbols, id inmappings, NSString *mappings);

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathDefaultTeXFont_addAlphabetWithId_withOrgScilabForgeJlatexmathCharacterCharacter_UnicodeBlockArray_withNSString_(id base, IOSObjectArray *alphabet, NSString *language);

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathDefaultTeXFont_addAlphabetWithOrgScilabForgeJlatexmathCharacterCharacter_UnicodeBlock_withNSString_(OrgScilabForgeJlatexmathCharacterCharacter_UnicodeBlock *alphabet, NSString *name);

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathDefaultTeXFont_addAlphabetWithOrgScilabForgeJlatexmathAlphabetRegistration_(id<OrgScilabForgeJlatexmathAlphabetRegistration> reg);

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathDefaultTeXFont_registerAlphabetWithOrgScilabForgeJlatexmathAlphabetRegistration_(id<OrgScilabForgeJlatexmathAlphabetRegistration> reg);

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathDefaultTeXFont_setMathSizesWithFloat_withFloat_withFloat_withFloat_(jfloat ds, jfloat ts, jfloat ss, jfloat sss);

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathDefaultTeXFont_setMagnificationWithFloat_(jfloat mag);

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathDefaultTeXFont_enableMagnificationWithBoolean_(jboolean b);

FOUNDATION_EXPORT jfloat OrgScilabForgeJlatexmathDefaultTeXFont_getSizeFactorWithInt_(jint style);

J2OBJC_TYPE_LITERAL_HEADER(OrgScilabForgeJlatexmathDefaultTeXFont)

#endif // _OrgScilabForgeJlatexmathDefaultTeXFont_H_
