//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/JLaTeXMath-iOS/JLaTeXMath-iOS/jlatexmath-share/org/scilab/forge/jlatexmath/FencedAtom.java
//

#ifndef _OrgScilabForgeJlatexmathFencedAtom_H_
#define _OrgScilabForgeJlatexmathFencedAtom_H_

#include "J2ObjC_header.h"
#include "org/scilab/forge/jlatexmath/Atom.h"

@class OrgScilabForgeJlatexmathBox;
@class OrgScilabForgeJlatexmathSymbolAtom;
@class OrgScilabForgeJlatexmathTeXEnvironment;
@protocol JavaUtilList;

@interface OrgScilabForgeJlatexmathFencedAtom : OrgScilabForgeJlatexmathAtom

#pragma mark Public

- (instancetype)initWithOrgScilabForgeJlatexmathAtom:(OrgScilabForgeJlatexmathAtom *)base
              withOrgScilabForgeJlatexmathSymbolAtom:(OrgScilabForgeJlatexmathSymbolAtom *)l
                                    withJavaUtilList:(id<JavaUtilList>)m
              withOrgScilabForgeJlatexmathSymbolAtom:(OrgScilabForgeJlatexmathSymbolAtom *)r;

- (instancetype)initWithOrgScilabForgeJlatexmathAtom:(OrgScilabForgeJlatexmathAtom *)base
              withOrgScilabForgeJlatexmathSymbolAtom:(OrgScilabForgeJlatexmathSymbolAtom *)l
              withOrgScilabForgeJlatexmathSymbolAtom:(OrgScilabForgeJlatexmathSymbolAtom *)r;

- (OrgScilabForgeJlatexmathBox *)createBoxWithOrgScilabForgeJlatexmathTeXEnvironment:(OrgScilabForgeJlatexmathTeXEnvironment *)env;

- (jint)getLeftType;

- (jint)getRightType;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgScilabForgeJlatexmathFencedAtom)

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathFencedAtom_initWithOrgScilabForgeJlatexmathAtom_withOrgScilabForgeJlatexmathSymbolAtom_withOrgScilabForgeJlatexmathSymbolAtom_(OrgScilabForgeJlatexmathFencedAtom *self, OrgScilabForgeJlatexmathAtom *base, OrgScilabForgeJlatexmathSymbolAtom *l, OrgScilabForgeJlatexmathSymbolAtom *r);

FOUNDATION_EXPORT OrgScilabForgeJlatexmathFencedAtom *new_OrgScilabForgeJlatexmathFencedAtom_initWithOrgScilabForgeJlatexmathAtom_withOrgScilabForgeJlatexmathSymbolAtom_withOrgScilabForgeJlatexmathSymbolAtom_(OrgScilabForgeJlatexmathAtom *base, OrgScilabForgeJlatexmathSymbolAtom *l, OrgScilabForgeJlatexmathSymbolAtom *r) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathFencedAtom_initWithOrgScilabForgeJlatexmathAtom_withOrgScilabForgeJlatexmathSymbolAtom_withJavaUtilList_withOrgScilabForgeJlatexmathSymbolAtom_(OrgScilabForgeJlatexmathFencedAtom *self, OrgScilabForgeJlatexmathAtom *base, OrgScilabForgeJlatexmathSymbolAtom *l, id<JavaUtilList> m, OrgScilabForgeJlatexmathSymbolAtom *r);

FOUNDATION_EXPORT OrgScilabForgeJlatexmathFencedAtom *new_OrgScilabForgeJlatexmathFencedAtom_initWithOrgScilabForgeJlatexmathAtom_withOrgScilabForgeJlatexmathSymbolAtom_withJavaUtilList_withOrgScilabForgeJlatexmathSymbolAtom_(OrgScilabForgeJlatexmathAtom *base, OrgScilabForgeJlatexmathSymbolAtom *l, id<JavaUtilList> m, OrgScilabForgeJlatexmathSymbolAtom *r) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgScilabForgeJlatexmathFencedAtom)

#endif // _OrgScilabForgeJlatexmathFencedAtom_H_
