//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/JLaTeXMath-iOS/JLaTeXMath-iOS/jlatexmath-share/org/scilab/forge/jlatexmath/GlueBox.java
//


#include "J2ObjC_source.h"
#include "org/scilab/forge/jlatexmath/Box.h"
#include "org/scilab/forge/jlatexmath/GlueBox.h"
#include "org/scilab/forge/jlatexmath/TeXFont.h"
#include "org/scilab/forge/jlatexmath/platform/graphics/Graphics2DInterface.h"

@implementation OrgScilabForgeJlatexmathGlueBox

- (instancetype)initWithFloat:(jfloat)space
                    withFloat:(jfloat)stretch
                    withFloat:(jfloat)shrink {
  OrgScilabForgeJlatexmathGlueBox_initWithFloat_withFloat_withFloat_(self, space, stretch, shrink);
  return self;
}

- (void)drawWithOrgScilabForgeJlatexmathPlatformGraphicsGraphics2DInterface:(id<OrgScilabForgeJlatexmathPlatformGraphicsGraphics2DInterface>)g2
                                                                  withFloat:(jfloat)x
                                                                  withFloat:(jfloat)y {
}

- (jint)getLastFontId {
  return OrgScilabForgeJlatexmathTeXFont_NO_FONT;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithFloat:withFloat:withFloat:", "GlueBox", NULL, 0x1, NULL, NULL },
    { "drawWithOrgScilabForgeJlatexmathPlatformGraphicsGraphics2DInterface:withFloat:withFloat:", "draw", "V", 0x1, NULL, NULL },
    { "getLastFontId", NULL, "I", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "stretch_", NULL, 0x4, "F", NULL, NULL,  },
    { "shrink_", NULL, 0x4, "F", NULL, NULL,  },
  };
  static const J2ObjcClassInfo _OrgScilabForgeJlatexmathGlueBox = { 2, "GlueBox", "org.scilab.forge.jlatexmath", NULL, 0x1, 3, methods, 2, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgScilabForgeJlatexmathGlueBox;
}

@end

void OrgScilabForgeJlatexmathGlueBox_initWithFloat_withFloat_withFloat_(OrgScilabForgeJlatexmathGlueBox *self, jfloat space, jfloat stretch, jfloat shrink) {
  OrgScilabForgeJlatexmathBox_init(self);
  self->stretch_ = 0;
  self->shrink_ = 0;
  self->width_ = space;
  self->stretch_ = stretch;
  self->shrink_ = shrink;
}

OrgScilabForgeJlatexmathGlueBox *new_OrgScilabForgeJlatexmathGlueBox_initWithFloat_withFloat_withFloat_(jfloat space, jfloat stretch, jfloat shrink) {
  OrgScilabForgeJlatexmathGlueBox *self = [OrgScilabForgeJlatexmathGlueBox alloc];
  OrgScilabForgeJlatexmathGlueBox_initWithFloat_withFloat_withFloat_(self, space, stretch, shrink);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgScilabForgeJlatexmathGlueBox)
