//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/JLaTeXMath-iOS/JLaTeXMath-iOS/jlatexmath-share/org/scilab/forge/jlatexmath/IddotsAtom.java
//

#ifndef _OrgScilabForgeJlatexmathIddotsAtom_H_
#define _OrgScilabForgeJlatexmathIddotsAtom_H_

#include "J2ObjC_header.h"
#include "org/scilab/forge/jlatexmath/Atom.h"

@class OrgScilabForgeJlatexmathBox;
@class OrgScilabForgeJlatexmathTeXEnvironment;

@interface OrgScilabForgeJlatexmathIddotsAtom : OrgScilabForgeJlatexmathAtom

#pragma mark Public

- (instancetype)init;

- (OrgScilabForgeJlatexmathBox *)createBoxWithOrgScilabForgeJlatexmathTeXEnvironment:(OrgScilabForgeJlatexmathTeXEnvironment *)env;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgScilabForgeJlatexmathIddotsAtom)

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathIddotsAtom_init(OrgScilabForgeJlatexmathIddotsAtom *self);

FOUNDATION_EXPORT OrgScilabForgeJlatexmathIddotsAtom *new_OrgScilabForgeJlatexmathIddotsAtom_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgScilabForgeJlatexmathIddotsAtom)

#endif // _OrgScilabForgeJlatexmathIddotsAtom_H_
