//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/JLaTeXMath-iOS/JLaTeXMath-iOS/jlatexmath-share/org/scilab/forge/jlatexmath/MiddleAtom.java
//

#ifndef _OrgScilabForgeJlatexmathMiddleAtom_H_
#define _OrgScilabForgeJlatexmathMiddleAtom_H_

#include "J2ObjC_header.h"
#include "org/scilab/forge/jlatexmath/Atom.h"

@class OrgScilabForgeJlatexmathBox;
@class OrgScilabForgeJlatexmathTeXEnvironment;

@interface OrgScilabForgeJlatexmathMiddleAtom : OrgScilabForgeJlatexmathAtom {
 @public
  OrgScilabForgeJlatexmathAtom *base_;
  OrgScilabForgeJlatexmathBox *box_;
}

#pragma mark Public

- (instancetype)initWithOrgScilabForgeJlatexmathAtom:(OrgScilabForgeJlatexmathAtom *)at;

- (OrgScilabForgeJlatexmathBox *)createBoxWithOrgScilabForgeJlatexmathTeXEnvironment:(OrgScilabForgeJlatexmathTeXEnvironment *)env;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgScilabForgeJlatexmathMiddleAtom)

J2OBJC_FIELD_SETTER(OrgScilabForgeJlatexmathMiddleAtom, base_, OrgScilabForgeJlatexmathAtom *)
J2OBJC_FIELD_SETTER(OrgScilabForgeJlatexmathMiddleAtom, box_, OrgScilabForgeJlatexmathBox *)

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathMiddleAtom_initWithOrgScilabForgeJlatexmathAtom_(OrgScilabForgeJlatexmathMiddleAtom *self, OrgScilabForgeJlatexmathAtom *at);

FOUNDATION_EXPORT OrgScilabForgeJlatexmathMiddleAtom *new_OrgScilabForgeJlatexmathMiddleAtom_initWithOrgScilabForgeJlatexmathAtom_(OrgScilabForgeJlatexmathAtom *at) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgScilabForgeJlatexmathMiddleAtom)

#endif // _OrgScilabForgeJlatexmathMiddleAtom_H_
