//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/JLaTeXMath-iOS/JLaTeXMath-iOS/jlatexmath-share/org/scilab/forge/jlatexmath/PhantomAtom.java
//

#ifndef _OrgScilabForgeJlatexmathPhantomAtom_H_
#define _OrgScilabForgeJlatexmathPhantomAtom_H_

#include "J2ObjC_header.h"
#include "org/scilab/forge/jlatexmath/Atom.h"
#include "org/scilab/forge/jlatexmath/Row.h"

@class OrgScilabForgeJlatexmathBox;
@class OrgScilabForgeJlatexmathDummy;
@class OrgScilabForgeJlatexmathTeXEnvironment;

@interface OrgScilabForgeJlatexmathPhantomAtom : OrgScilabForgeJlatexmathAtom < OrgScilabForgeJlatexmathRow >

#pragma mark Public

- (instancetype)initWithOrgScilabForgeJlatexmathAtom:(OrgScilabForgeJlatexmathAtom *)el;

- (instancetype)initWithOrgScilabForgeJlatexmathAtom:(OrgScilabForgeJlatexmathAtom *)el
                                         withBoolean:(jboolean)width
                                         withBoolean:(jboolean)height
                                         withBoolean:(jboolean)depth;

- (OrgScilabForgeJlatexmathBox *)createBoxWithOrgScilabForgeJlatexmathTeXEnvironment:(OrgScilabForgeJlatexmathTeXEnvironment *)env;

- (jint)getLeftType;

- (jint)getRightType;

- (void)setPreviousAtomWithOrgScilabForgeJlatexmathDummy:(OrgScilabForgeJlatexmathDummy *)prev;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgScilabForgeJlatexmathPhantomAtom)

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathPhantomAtom_initWithOrgScilabForgeJlatexmathAtom_(OrgScilabForgeJlatexmathPhantomAtom *self, OrgScilabForgeJlatexmathAtom *el);

FOUNDATION_EXPORT OrgScilabForgeJlatexmathPhantomAtom *new_OrgScilabForgeJlatexmathPhantomAtom_initWithOrgScilabForgeJlatexmathAtom_(OrgScilabForgeJlatexmathAtom *el) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathPhantomAtom_initWithOrgScilabForgeJlatexmathAtom_withBoolean_withBoolean_withBoolean_(OrgScilabForgeJlatexmathPhantomAtom *self, OrgScilabForgeJlatexmathAtom *el, jboolean width, jboolean height, jboolean depth);

FOUNDATION_EXPORT OrgScilabForgeJlatexmathPhantomAtom *new_OrgScilabForgeJlatexmathPhantomAtom_initWithOrgScilabForgeJlatexmathAtom_withBoolean_withBoolean_withBoolean_(OrgScilabForgeJlatexmathAtom *el, jboolean width, jboolean height, jboolean depth) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgScilabForgeJlatexmathPhantomAtom)

#endif // _OrgScilabForgeJlatexmathPhantomAtom_H_
