//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/JLaTeXMath-iOS/JLaTeXMath-iOS/jlatexmath-share/org/scilab/forge/jlatexmath/SymbolAtom.java
//

#ifndef _OrgScilabForgeJlatexmathSymbolAtom_H_
#define _OrgScilabForgeJlatexmathSymbolAtom_H_

#include "J2ObjC_header.h"
#include "org/scilab/forge/jlatexmath/CharSymbol.h"

@class OrgScilabForgeJlatexmathBox;
@class OrgScilabForgeJlatexmathCharFont;
@class OrgScilabForgeJlatexmathTeXEnvironment;
@protocol JavaUtilMap;
@protocol OrgScilabForgeJlatexmathTeXFont;

@interface OrgScilabForgeJlatexmathSymbolAtom : OrgScilabForgeJlatexmathCharSymbol

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)name
                         withInt:(jint)type
                     withBoolean:(jboolean)del;

- (instancetype)initWithOrgScilabForgeJlatexmathSymbolAtom:(OrgScilabForgeJlatexmathSymbolAtom *)s
                                                   withInt:(jint)type;

+ (void)addSymbolAtomWithId:(id)inArg
               withNSString:(NSString *)name;

+ (void)addSymbolAtomWithNSString:(NSString *)file;

+ (void)addSymbolAtomWithOrgScilabForgeJlatexmathSymbolAtom:(OrgScilabForgeJlatexmathSymbolAtom *)sym;

- (OrgScilabForgeJlatexmathBox *)createBoxWithOrgScilabForgeJlatexmathTeXEnvironment:(OrgScilabForgeJlatexmathTeXEnvironment *)env;

+ (OrgScilabForgeJlatexmathSymbolAtom *)getWithNSString:(NSString *)name;

- (OrgScilabForgeJlatexmathCharFont *)getCharFontWithOrgScilabForgeJlatexmathTeXFont:(id<OrgScilabForgeJlatexmathTeXFont>)tf;

- (NSString *)getName;

- (jchar)getUnicode;

- (jboolean)isDelimiter;

- (OrgScilabForgeJlatexmathSymbolAtom *)setUnicodeWithChar:(jchar)c;

@end

J2OBJC_STATIC_INIT(OrgScilabForgeJlatexmathSymbolAtom)

FOUNDATION_EXPORT id<JavaUtilMap> OrgScilabForgeJlatexmathSymbolAtom_symbols_;
J2OBJC_STATIC_FIELD_GETTER(OrgScilabForgeJlatexmathSymbolAtom, symbols_, id<JavaUtilMap>)
J2OBJC_STATIC_FIELD_SETTER(OrgScilabForgeJlatexmathSymbolAtom, symbols_, id<JavaUtilMap>)

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathSymbolAtom_initWithOrgScilabForgeJlatexmathSymbolAtom_withInt_(OrgScilabForgeJlatexmathSymbolAtom *self, OrgScilabForgeJlatexmathSymbolAtom *s, jint type);

FOUNDATION_EXPORT OrgScilabForgeJlatexmathSymbolAtom *new_OrgScilabForgeJlatexmathSymbolAtom_initWithOrgScilabForgeJlatexmathSymbolAtom_withInt_(OrgScilabForgeJlatexmathSymbolAtom *s, jint type) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathSymbolAtom_initWithNSString_withInt_withBoolean_(OrgScilabForgeJlatexmathSymbolAtom *self, NSString *name, jint type, jboolean del);

FOUNDATION_EXPORT OrgScilabForgeJlatexmathSymbolAtom *new_OrgScilabForgeJlatexmathSymbolAtom_initWithNSString_withInt_withBoolean_(NSString *name, jint type, jboolean del) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathSymbolAtom_addSymbolAtomWithNSString_(NSString *file);

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathSymbolAtom_addSymbolAtomWithId_withNSString_(id inArg, NSString *name);

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathSymbolAtom_addSymbolAtomWithOrgScilabForgeJlatexmathSymbolAtom_(OrgScilabForgeJlatexmathSymbolAtom *sym);

FOUNDATION_EXPORT OrgScilabForgeJlatexmathSymbolAtom *OrgScilabForgeJlatexmathSymbolAtom_getWithNSString_(NSString *name);

J2OBJC_TYPE_LITERAL_HEADER(OrgScilabForgeJlatexmathSymbolAtom)

#endif // _OrgScilabForgeJlatexmathSymbolAtom_H_
