//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/JLaTeXMath-iOS/JLaTeXMath-iOS/jlatexmath-share/org/scilab/forge/jlatexmath/TeXEnvironment.java
//

#ifndef _OrgScilabForgeJlatexmathTeXEnvironment_H_
#define _OrgScilabForgeJlatexmathTeXEnvironment_H_

#include "J2ObjC_header.h"

@protocol OrgScilabForgeJlatexmathPlatformGraphicsColor;
@protocol OrgScilabForgeJlatexmathTeXFont;

@interface OrgScilabForgeJlatexmathTeXEnvironment : NSObject {
 @public
  jboolean isColored_;
}

#pragma mark Public

- (instancetype)initWithInt:(jint)style
withOrgScilabForgeJlatexmathTeXFont:(id<OrgScilabForgeJlatexmathTeXFont>)tf;

- (instancetype)initWithInt:(jint)style
withOrgScilabForgeJlatexmathTeXFont:(id<OrgScilabForgeJlatexmathTeXFont>)tf
                    withInt:(jint)widthUnit
                  withFloat:(jfloat)textwidth;

- (OrgScilabForgeJlatexmathTeXEnvironment *)crampStyle;

- (OrgScilabForgeJlatexmathTeXEnvironment *)denomStyle;

- (id<OrgScilabForgeJlatexmathPlatformGraphicsColor>)getBackground;

- (id<OrgScilabForgeJlatexmathPlatformGraphicsColor>)getColor;

- (jfloat)getInterline;

- (jint)getLastFontId;

- (jfloat)getScaleFactor;

- (jfloat)getSize;

- (jboolean)getSmallCap;

- (jfloat)getSpace;

- (jint)getStyle;

- (id<OrgScilabForgeJlatexmathTeXFont>)getTeXFont;

- (NSString *)getTextStyle;

- (jfloat)getTextwidth;

- (OrgScilabForgeJlatexmathTeXEnvironment *)numStyle;

- (void)reset;

- (OrgScilabForgeJlatexmathTeXEnvironment *)rootStyle;

- (void)setBackgroundWithOrgScilabForgeJlatexmathPlatformGraphicsColor:(id<OrgScilabForgeJlatexmathPlatformGraphicsColor>)c;

- (void)setColorWithOrgScilabForgeJlatexmathPlatformGraphicsColor:(id<OrgScilabForgeJlatexmathPlatformGraphicsColor>)c;

- (void)setInterlineWithInt:(jint)unit
                  withFloat:(jfloat)len;

- (void)setLastFontIdWithInt:(jint)id_;

- (void)setScaleFactorWithFloat:(jfloat)f;

- (void)setSmallCapWithBoolean:(jboolean)smallCap;

- (void)setStyleWithInt:(jint)style;

- (void)setTextStyleWithNSString:(NSString *)textStyle;

- (void)setTextwidthWithInt:(jint)widthUnit
                  withFloat:(jfloat)textwidth;

- (OrgScilabForgeJlatexmathTeXEnvironment *)subStyle;

- (OrgScilabForgeJlatexmathTeXEnvironment *)supStyle;

#pragma mark Protected

- (OrgScilabForgeJlatexmathTeXEnvironment *)copy__ OBJC_METHOD_FAMILY_NONE;

- (OrgScilabForgeJlatexmathTeXEnvironment *)copy__WithOrgScilabForgeJlatexmathTeXFont:(id<OrgScilabForgeJlatexmathTeXFont>)tf OBJC_METHOD_FAMILY_NONE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgScilabForgeJlatexmathTeXEnvironment)

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathTeXEnvironment_initWithInt_withOrgScilabForgeJlatexmathTeXFont_(OrgScilabForgeJlatexmathTeXEnvironment *self, jint style, id<OrgScilabForgeJlatexmathTeXFont> tf);

FOUNDATION_EXPORT OrgScilabForgeJlatexmathTeXEnvironment *new_OrgScilabForgeJlatexmathTeXEnvironment_initWithInt_withOrgScilabForgeJlatexmathTeXFont_(jint style, id<OrgScilabForgeJlatexmathTeXFont> tf) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathTeXEnvironment_initWithInt_withOrgScilabForgeJlatexmathTeXFont_withInt_withFloat_(OrgScilabForgeJlatexmathTeXEnvironment *self, jint style, id<OrgScilabForgeJlatexmathTeXFont> tf, jint widthUnit, jfloat textwidth);

FOUNDATION_EXPORT OrgScilabForgeJlatexmathTeXEnvironment *new_OrgScilabForgeJlatexmathTeXEnvironment_initWithInt_withOrgScilabForgeJlatexmathTeXFont_withInt_withFloat_(jint style, id<OrgScilabForgeJlatexmathTeXFont> tf, jint widthUnit, jfloat textwidth) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgScilabForgeJlatexmathTeXEnvironment)

#endif // _OrgScilabForgeJlatexmathTeXEnvironment_H_
