//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/JLaTeXMath-iOS/JLaTeXMath-iOS/jlatexmath-share/org/scilab/forge/jlatexmath/TeXSymbolParser.java
//

#ifndef _OrgScilabForgeJlatexmathTeXSymbolParser_H_
#define _OrgScilabForgeJlatexmathTeXSymbolParser_H_

#include "J2ObjC_header.h"

@protocol JavaUtilMap;

@interface OrgScilabForgeJlatexmathTeXSymbolParser : NSObject

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithId:(id)file
              withNSString:(NSString *)name;

- (id<JavaUtilMap>)readSymbols;

@end

J2OBJC_STATIC_INIT(OrgScilabForgeJlatexmathTeXSymbolParser)

FOUNDATION_EXPORT NSString *OrgScilabForgeJlatexmathTeXSymbolParser_RESOURCE_NAME_;
J2OBJC_STATIC_FIELD_GETTER(OrgScilabForgeJlatexmathTeXSymbolParser, RESOURCE_NAME_, NSString *)

FOUNDATION_EXPORT NSString *OrgScilabForgeJlatexmathTeXSymbolParser_DELIMITER_ATTR_;
J2OBJC_STATIC_FIELD_GETTER(OrgScilabForgeJlatexmathTeXSymbolParser, DELIMITER_ATTR_, NSString *)

FOUNDATION_EXPORT NSString *OrgScilabForgeJlatexmathTeXSymbolParser_TYPE_ATTR_;
J2OBJC_STATIC_FIELD_GETTER(OrgScilabForgeJlatexmathTeXSymbolParser, TYPE_ATTR_, NSString *)

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathTeXSymbolParser_init(OrgScilabForgeJlatexmathTeXSymbolParser *self);

FOUNDATION_EXPORT OrgScilabForgeJlatexmathTeXSymbolParser *new_OrgScilabForgeJlatexmathTeXSymbolParser_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathTeXSymbolParser_initWithId_withNSString_(OrgScilabForgeJlatexmathTeXSymbolParser *self, id file, NSString *name);

FOUNDATION_EXPORT OrgScilabForgeJlatexmathTeXSymbolParser *new_OrgScilabForgeJlatexmathTeXSymbolParser_initWithId_withNSString_(id file, NSString *name) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgScilabForgeJlatexmathTeXSymbolParser)

#endif // _OrgScilabForgeJlatexmathTeXSymbolParser_H_
