//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/JLaTeXMath-iOS/JLaTeXMath-iOS/jlatexmath-share/org/scilab/forge/jlatexmath/exception/DelimiterMappingNotFoundException.java
//


#include "J2ObjC_source.h"
#include "org/scilab/forge/jlatexmath/TeXFormulaSettingsParser.h"
#include "org/scilab/forge/jlatexmath/exception/DelimiterMappingNotFoundException.h"
#include "org/scilab/forge/jlatexmath/exception/JMathTeXException.h"

@implementation OrgScilabForgeJlatexmathExceptionDelimiterMappingNotFoundException

- (instancetype)initWithChar:(jchar)delimiter {
  OrgScilabForgeJlatexmathExceptionDelimiterMappingNotFoundException_initWithChar_(self, delimiter);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithChar:", "DelimiterMappingNotFoundException", NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcClassInfo _OrgScilabForgeJlatexmathExceptionDelimiterMappingNotFoundException = { 2, "DelimiterMappingNotFoundException", "org.scilab.forge.jlatexmath.exception", NULL, 0x1, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgScilabForgeJlatexmathExceptionDelimiterMappingNotFoundException;
}

@end

void OrgScilabForgeJlatexmathExceptionDelimiterMappingNotFoundException_initWithChar_(OrgScilabForgeJlatexmathExceptionDelimiterMappingNotFoundException *self, jchar delimiter) {
  OrgScilabForgeJlatexmathExceptionJMathTeXException_initWithNSString_(self, JreStrcat("$C$$$$$", @"No mapping found for the character '", delimiter, @"'! Insert a <", OrgScilabForgeJlatexmathTeXFormulaSettingsParser_get_CHARTODEL_MAPPING_EL_(), @">-element in '", OrgScilabForgeJlatexmathTeXFormulaSettingsParser_get_RESOURCE_NAME_(), @"'."));
}

OrgScilabForgeJlatexmathExceptionDelimiterMappingNotFoundException *new_OrgScilabForgeJlatexmathExceptionDelimiterMappingNotFoundException_initWithChar_(jchar delimiter) {
  OrgScilabForgeJlatexmathExceptionDelimiterMappingNotFoundException *self = [OrgScilabForgeJlatexmathExceptionDelimiterMappingNotFoundException alloc];
  OrgScilabForgeJlatexmathExceptionDelimiterMappingNotFoundException_initWithChar_(self, delimiter);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgScilabForgeJlatexmathExceptionDelimiterMappingNotFoundException)
