//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/JLaTeXMath-iOS/JLaTeXMath-iOS/jlatexmath-share/org/scilab/forge/jlatexmath/exception/ResourceParseException.java
//

#ifndef _OrgScilabForgeJlatexmathExceptionResourceParseException_H_
#define _OrgScilabForgeJlatexmathExceptionResourceParseException_H_

#include "J2ObjC_header.h"
#include "org/scilab/forge/jlatexmath/exception/JMathTeXException.h"

@class JavaLangThrowable;

@interface OrgScilabForgeJlatexmathExceptionResourceParseException : OrgScilabForgeJlatexmathExceptionJMathTeXException

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)msg;

- (instancetype)initWithNSString:(NSString *)msg
           withJavaLangThrowable:(JavaLangThrowable *)cause;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgScilabForgeJlatexmathExceptionResourceParseException)

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathExceptionResourceParseException_initWithNSString_(OrgScilabForgeJlatexmathExceptionResourceParseException *self, NSString *msg);

FOUNDATION_EXPORT OrgScilabForgeJlatexmathExceptionResourceParseException *new_OrgScilabForgeJlatexmathExceptionResourceParseException_initWithNSString_(NSString *msg) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathExceptionResourceParseException_initWithNSString_withJavaLangThrowable_(OrgScilabForgeJlatexmathExceptionResourceParseException *self, NSString *msg, JavaLangThrowable *cause);

FOUNDATION_EXPORT OrgScilabForgeJlatexmathExceptionResourceParseException *new_OrgScilabForgeJlatexmathExceptionResourceParseException_initWithNSString_withJavaLangThrowable_(NSString *msg, JavaLangThrowable *cause) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgScilabForgeJlatexmathExceptionResourceParseException)

#endif // _OrgScilabForgeJlatexmathExceptionResourceParseException_H_
