//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/JLaTeXMath-iOS/JLaTeXMath-iOS/jlatexmath-share/org/scilab/forge/jlatexmath/platform/geom/GeomFactory.java
//

#ifndef _OrgScilabForgeJlatexmathPlatformGeomGeomFactory_H_
#define _OrgScilabForgeJlatexmathPlatformGeomGeomFactory_H_

#include "J2ObjC_header.h"

@protocol OrgScilabForgeJlatexmathPlatformGeomLine2D;
@protocol OrgScilabForgeJlatexmathPlatformGeomPoint2D;
@protocol OrgScilabForgeJlatexmathPlatformGeomRectangle2D;
@protocol OrgScilabForgeJlatexmathPlatformGeomRoundRectangle2D;

@interface OrgScilabForgeJlatexmathPlatformGeomGeomFactory : NSObject

#pragma mark Public

- (instancetype)init;

- (id<OrgScilabForgeJlatexmathPlatformGeomLine2D>)createLine2DWithDouble:(jdouble)x1
                                                              withDouble:(jdouble)y1
                                                              withDouble:(jdouble)x2
                                                              withDouble:(jdouble)y2;

- (id<OrgScilabForgeJlatexmathPlatformGeomPoint2D>)createPoint2DWithDouble:(jdouble)x
                                                                withDouble:(jdouble)y;

- (id<OrgScilabForgeJlatexmathPlatformGeomRectangle2D>)createRectangle2DWithDouble:(jdouble)x
                                                                        withDouble:(jdouble)y
                                                                        withDouble:(jdouble)w
                                                                        withDouble:(jdouble)h;

- (id<OrgScilabForgeJlatexmathPlatformGeomRoundRectangle2D>)createRoundRectangle2DWithDouble:(jdouble)x
                                                                                  withDouble:(jdouble)y
                                                                                  withDouble:(jdouble)w
                                                                                  withDouble:(jdouble)h
                                                                                  withDouble:(jdouble)arcw
                                                                                  withDouble:(jdouble)arch;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgScilabForgeJlatexmathPlatformGeomGeomFactory)

FOUNDATION_EXPORT void OrgScilabForgeJlatexmathPlatformGeomGeomFactory_init(OrgScilabForgeJlatexmathPlatformGeomGeomFactory *self);

J2OBJC_TYPE_LITERAL_HEADER(OrgScilabForgeJlatexmathPlatformGeomGeomFactory)

#endif // _OrgScilabForgeJlatexmathPlatformGeomGeomFactory_H_
