//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/JLaTeXMath-iOS/JLaTeXMath-iOS/jlatexmath-share/org/scilab/forge/jlatexmath/platform/geom/Line2D.java
//

#ifndef _OrgScilabForgeJlatexmathPlatformGeomLine2D_H_
#define _OrgScilabForgeJlatexmathPlatformGeomLine2D_H_

#include "J2ObjC_header.h"

@protocol OrgScilabForgeJlatexmathPlatformGeomLine2D < NSObject, JavaObject >

- (jdouble)getX1;

- (jdouble)getY1;

- (jdouble)getX2;

- (jdouble)getY2;

- (void)setLineWithDouble:(jdouble)x1
               withDouble:(jdouble)y1
               withDouble:(jdouble)x2
               withDouble:(jdouble)y2;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgScilabForgeJlatexmathPlatformGeomLine2D)

J2OBJC_TYPE_LITERAL_HEADER(OrgScilabForgeJlatexmathPlatformGeomLine2D)

@protocol OrgScilabForgeJlatexmathPlatformGeomLine2D_Float < OrgScilabForgeJlatexmathPlatformGeomLine2D, NSObject, JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(OrgScilabForgeJlatexmathPlatformGeomLine2D_Float)

J2OBJC_TYPE_LITERAL_HEADER(OrgScilabForgeJlatexmathPlatformGeomLine2D_Float)

#endif // _OrgScilabForgeJlatexmathPlatformGeomLine2D_H_
