//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/JLaTeXMath-iOS/JLaTeXMath-iOS/jlatexmath-share/org/scilab/forge/jlatexmath/platform/geom/Rectangle2D.java
//

#ifndef _OrgScilabForgeJlatexmathPlatformGeomRectangle2D_H_
#define _OrgScilabForgeJlatexmathPlatformGeomRectangle2D_H_

#include "J2ObjC_header.h"

@protocol OrgScilabForgeJlatexmathPlatformGeomRectangle2D < NSObject, JavaObject >

- (jdouble)getX;

- (jdouble)getY;

- (jdouble)getWidth;

- (jdouble)getHeight;

- (void)setRectangleWithDouble:(jdouble)x
                    withDouble:(jdouble)y
                    withDouble:(jdouble)width
                    withDouble:(jdouble)height;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgScilabForgeJlatexmathPlatformGeomRectangle2D)

J2OBJC_TYPE_LITERAL_HEADER(OrgScilabForgeJlatexmathPlatformGeomRectangle2D)

@protocol OrgScilabForgeJlatexmathPlatformGeomRectangle2D_Float < OrgScilabForgeJlatexmathPlatformGeomRectangle2D, NSObject, JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(OrgScilabForgeJlatexmathPlatformGeomRectangle2D_Float)

J2OBJC_TYPE_LITERAL_HEADER(OrgScilabForgeJlatexmathPlatformGeomRectangle2D_Float)

#endif // _OrgScilabForgeJlatexmathPlatformGeomRectangle2D_H_
