//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/JLaTeXMath-iOS/JLaTeXMath-iOS/jlatexmath-share/org/scilab/forge/jlatexmath/platform/geom/RoundRectangle2D.java
//

#ifndef _OrgScilabForgeJlatexmathPlatformGeomRoundRectangle2D_H_
#define _OrgScilabForgeJlatexmathPlatformGeomRoundRectangle2D_H_

#include "J2ObjC_header.h"

@protocol OrgScilabForgeJlatexmathPlatformGeomRoundRectangle2D < NSObject, JavaObject >

- (jdouble)getArcW;

- (jdouble)getArcH;

- (jdouble)getX;

- (jdouble)getY;

- (jdouble)getWidth;

- (jdouble)getHeight;

- (void)setRoundRectangleWithDouble:(jdouble)x
                         withDouble:(jdouble)y
                         withDouble:(jdouble)w
                         withDouble:(jdouble)h
                         withDouble:(jdouble)arcw
                         withDouble:(jdouble)arch;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgScilabForgeJlatexmathPlatformGeomRoundRectangle2D)

J2OBJC_TYPE_LITERAL_HEADER(OrgScilabForgeJlatexmathPlatformGeomRoundRectangle2D)

@protocol OrgScilabForgeJlatexmathPlatformGeomRoundRectangle2D_Float < OrgScilabForgeJlatexmathPlatformGeomRoundRectangle2D, NSObject, JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(OrgScilabForgeJlatexmathPlatformGeomRoundRectangle2D_Float)

J2OBJC_TYPE_LITERAL_HEADER(OrgScilabForgeJlatexmathPlatformGeomRoundRectangle2D_Float)

#endif // _OrgScilabForgeJlatexmathPlatformGeomRoundRectangle2D_H_
