//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/JLaTeXMath-iOS/JLaTeXMath-iOS/jlatexmath-share/org/scilab/forge/jlatexmath/platform/resources/ResourceLoaderFactory.java
//

#ifndef _OrgScilabForgeJlatexmathPlatformResourcesResourceLoaderFactory_H_
#define _OrgScilabForgeJlatexmathPlatformResourcesResourceLoaderFactory_H_

#include "J2ObjC_header.h"

@protocol OrgScilabForgeJlatexmathPlatformResourcesResourceLoader;

@protocol OrgScilabForgeJlatexmathPlatformResourcesResourceLoaderFactory < NSObject, JavaObject >

- (id<OrgScilabForgeJlatexmathPlatformResourcesResourceLoader>)createResourceLoader;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgScilabForgeJlatexmathPlatformResourcesResourceLoaderFactory)

J2OBJC_TYPE_LITERAL_HEADER(OrgScilabForgeJlatexmathPlatformResourcesResourceLoaderFactory)

#endif // _OrgScilabForgeJlatexmathPlatformResourcesResourceLoaderFactory_H_
