//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/JLaTeXMath-iOS/JLaTeXMath-iOS/jlatexmath-share/org/scilab/forge/jlatexmath/platform/resources/ResourceLoader.java
//

#ifndef _OrgScilabForgeJlatexmathPlatformResourcesResourceLoader_H_
#define _OrgScilabForgeJlatexmathPlatformResourcesResourceLoader_H_

#include "J2ObjC_header.h"

@protocol OrgScilabForgeJlatexmathPlatformResourcesResourceLoader < NSObject, JavaObject >

- (id)loadResourceWithId:(id)base
            withNSString:(NSString *)path;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgScilabForgeJlatexmathPlatformResourcesResourceLoader)

J2OBJC_TYPE_LITERAL_HEADER(OrgScilabForgeJlatexmathPlatformResourcesResourceLoader)

#endif // _OrgScilabForgeJlatexmathPlatformResourcesResourceLoader_H_
