//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/jacky/GSoC/JLaTeXMath-iOS/JLaTeXMath-iOS/jlatexmath-share/org/scilab/forge/jlatexmath/dynamic/ExternalConverterFactory.java
//

#ifndef _OrgScilabForgeJlatexmathDynamicExternalConverterFactory_H_
#define _OrgScilabForgeJlatexmathDynamicExternalConverterFactory_H_

#include "J2ObjC_header.h"

@protocol OrgScilabForgeJlatexmathDynamicExternalConverter;

@protocol OrgScilabForgeJlatexmathDynamicExternalConverterFactory < NSObject, JavaObject >

- (id<OrgScilabForgeJlatexmathDynamicExternalConverter>)getExternalConverter;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgScilabForgeJlatexmathDynamicExternalConverterFactory)

J2OBJC_TYPE_LITERAL_HEADER(OrgScilabForgeJlatexmathDynamicExternalConverterFactory)

#endif // _OrgScilabForgeJlatexmathDynamicExternalConverterFactory_H_
